### ISSUE TITLE
展示物品玩家掉线问题

### ISSUE THREAD

**Issue by Moki0** [FlickerProjects/TrChat#10]
群组服，子服核心paper-1.16.5

玩家使用 %i 展示头颅时，会导致一些玩家掉线。
之前是不管展示什么只要 %i%i 都会掉线，现在变成了展示头颅掉线。

图片：https://i.loli.net/2021/08/26/imRouDPxCvSYJcj.png

**Comment by MCZQ** [comment]
我也遇到了同样的问题，我是玩家/global %i 然后就会导致大部分玩家突然掉线
![C)FB(~)NZ{C@_$FOJYCYO48](https://user-images.githubusercontent.com/56064852/131286539-6ed8d5e1-bee8-4495-b653-085521134ea6.png)

**Comment by MCZQ** [comment]
emm..这好像是个重大的bug，请大佬修复一下吧

**Comment by ItsFlicker** [comment]
请测试最新构建是否有此问题

**Comment by MCZQ** [comment]
1.9版本的仍然有此问题

**Comment by ItsFlicker** [comment]
> 1.9版本的仍然有此问题

请尝试将function.yml中的GENERAL.ITEM-SHOW.COMPATIBLE设为true

**Comment by JinOuYongGu** [comment]
同样出现此类问题，当展示物品的自定义名称较长时会出现掉线。

**Comment by ItsFlicker** [comment]
@JinOuYongGu 请使用trmenu将物品序列化以供测试

**Comment by xiangxiangxiong9** [comment]
我这也遇到了展示物品导致玩家掉线的问题
部分日志 [Error.log](https://github.com/FlickerProjects/TrChat/files/7914384/Error.log)
---
Waterfall-475 Paper-1.16.5 ViaVersion-4.1.1 ViaBackwards-4.1.1

**Comment by ItsFlicker** [comment]
减少了部分此问题

**Comment by ItsFlicker** [comment]
Fixed in 2.0
