### ISSUE TITLE
对于2.0版本不显示hover

### ISSUE THREAD

**Issue by DreamMiu** [FlickerProjects/TrChat#103]
对于2.0后重新配置和，默认配置都没有显示hover: 里面的内容了

核心:Pufferfish1.18.2
JDK:17
winserver 2016

**Comment by ItsFlicker** [comment]
2.0.0-PRE-2已修复

**Comment by DreamMiu** [comment]
> 2.0.0-PRE-2 已修复

自己构建嘛awa

**Comment by ItsFlicker** [comment]
..忘提交了
