### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by konsheng** [FlickerProjects/TrChat#108]
### 在发送消息时增加自定义SOUND音效，顺便与PLyerMoreSound兼容下，此插件也有音效，可能会造成冲突，导致发出两种音效。

**Comment by konsheng** [comment]
### 支持@nick名称
##
ess，cmi的nick名称功能

**Comment by konsheng** [comment]
### 给聊天颜色增加命令切换功能
##

输入/trchat color red使用红色（以此类推），与trchat.color.<CODE>绑定

方便玩家使用GUI选择聊天颜色，使用权限的话得一会上权限一会下权限，过于麻烦

修改配置文件创建多组来实现会导致大量重复内容，过于麻烦

**Comment by ItsFlicker** [comment]
> 给聊天颜色增加命令切换功能
> 在发送消息时增加自定义SOUND音效

将会在2.0.0-PRE-13支持

**Comment by ItsFlicker** [comment]
> ### 在发送消息时增加自定义SOUND音效，顺便与PLyerMoreSound兼容下，此插件也有音效，可能会造成冲突，导致发出两种音效。

添加
```yaml
Events:
  Send: |-
    sound ...
```
实现

**Comment by ItsFlicker** [comment]
> ### 给聊天颜色增加命令切换功能
> 输入/trchat color red使用红色（以此类推），与trchat.color.`绑定`
> 
> ` 方便玩家使用GUI选择聊天颜色，使用权限的话得一会上权限一会下权限，过于麻烦 修改配置文件创建多组来实现会导致大量重复内容，过于麻烦`

已完成

**Comment by ItsFlicker** [comment]
在RC-1中支持@nickname 但仅限在同一个子服内
