### ISSUE TITLE
TrChat1.90-R4不能识别ItemsAdder发出的Emoji

### ISSUE THREAD

**Issue by cnluminous** [FlickerProjects/TrChat#109]
出现在公屏聊天内，私聊可以正常显示Emoji，除了公屏以外的地方均可正常显示Emoji，原版聊天功能以及CMI，Essentials聊天功能也均能正常使用
服务器插件列表:
(22): AdvancedColorAPI, Chunkmaster, CMI, CMILib, ItemsAdder, LibsDisguises, LightAPI, LoneLibs, LuckPerms, MiaoNashorn, ModelEngine, Multiverse-Core*, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, Residence, ScreenEffects, spark, TAB, TrChat, TrMenu, Vault
插件均为最新版本插件，部分付费插件为Spigotmc.org正版插件

**Comment by cnluminous** [comment]
![image](https://user-images.githubusercontent.com/47070284/164284060-95cc4506-817a-46c9-99f4-0a95d76f42a0.png)

**Comment by cnluminous** [comment]
插件数量大于12个插件时，无法正常使用

**Comment by konsheng** [comment]
### 1.9版本已停止支持，请使用2.0版本TrChat
https://github.com/FlickerProjects/TrChat/actions
