### ISSUE TITLE
网易BC核心无法加载插件

### ISSUE THREAD

**Issue by byxiaobai** [FlickerProjects/TrChat#11]
![I(DNFI7JV%_SR_ZUEPY`K_E](https://user-images.githubusercontent.com/26520933/131626959-ba6dac23-70b3-4502-a611-0475b90a5a15.png)

**Comment by byxiaobai** [comment]
[BungeeCord.zip](https://github.com/FlickerProjects/TrChat/files/7088950/BungeeCord.zip)

**Comment by 157946a** [comment]
跟插件无关,你bc都多老了,把你bc核心给更了就行了,没什么问题
