### ISSUE TITLE
[建议] 由服务器发出的全服消息

### ISSUE THREAD

**Issue by 849025143** [FlickerProjects/TrChat#110]
举个例子：
A服务器控制台发送命令 /trchat broadcast 啊啊啊啊啊 即可发送至每一个服务器
相关功能：
喊话功能 /all XXX 
让它可以支持控制台执行

**Comment by ItsFlicker** [comment]
2.0.0-PRE7 已支持

**Comment by 849025143** [comment]
> 

构建失败了，下载不了。

**Comment by 157946a** [comment]
https://github.com/FlickerProjects/TrChat/actions/runs/2323081084 前往下载
