### ISSUE TITLE
增加屏蔽功能

### ISSUE THREAD

**Issue by Dreeam-qwq** [FlickerProjects/TrChat#116]
增加一个玩家可以屏蔽另外一个玩家消息的功能，/ignore。
毕竟装了trchat之后，ess的ignore貌似不能屏蔽消息

**Comment by hexadecimal233** [comment]
@ItsFlicker

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/2560479915 已支持
