### ISSUE TITLE
在Paper服务器上Trchat与PlaceholderAPI冲突

### ISSUE THREAD

**Issue by MikkoAyaka** [FlickerProjects/TrChat#117]
单独进行了测试，用Paper官网318版本的服务端核心，只安装Trchat和PlaceholderAPI两个插件，
然后启动，没有报错，随便给PlaceholderAPI下载几个拓展，player，server之类的，然后关服重启。
之后再启动服务器，会导致PAPI无法正常加载它的拓展，必须手动papi reload一次才能正常加载。

**Comment by hexadecimal233** [comment]
server插件的通病

**Comment by 157946a** [comment]
> server插件的通病

是扩展

**Comment by hexadecimal233** [comment]
> > server插件的通病
> 
> 是扩展

[试试这个](https://github.com/PlaceholderAPI/Server-Expansion/pull/46)

**Comment by 157946a** [comment]
> > > server插件的通病
> > 
> > 
> > 是扩展
> 
> [试试这个](https://github.com/PlaceholderAPI/Server-Expansion/pull/46)

.........听不懂吗,我说了解决方法,不需要你再来

**Comment by 157946a** [comment]
使用最新构建
