### ISSUE TITLE
Global频道无法屏蔽内容

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [FlickerProjects/TrChat#118]
我服是说话默认全局同步的，实测这样屏蔽词无法生效

**Comment by Aira-Sakuranomiya** [comment]
希望能在把消息发到BC之前经过一下filter过滤

**Comment by ItsFlicker** [comment]
2.0.0-PRE5已支持
在频道文件里Options里添加Filter-Before-Sending: true就可以了

**Comment by Aira-Sakuranomiya** [comment]
Nice ♥

**Comment by xANoyU** [comment]
> 2.0.0-PRE5已支持 在频道文件里Options里添加Filter-Before-Sending: true就可以了



> 2.0.0-PRE5已支持 在频道文件里Options里添加Filter-Before-Sending: true就可以了
![QQ截图20220619234954](https://user-images.githubusercontent.com/62326160/174489548-d179acfd-7349-45ce-9ad1-fdcd3ca7f239.png)
![QQ截图20220619235019](https://user-images.githubusercontent.com/62326160/174489551-6339d233-8015-467a-91ad-d4336b824ce0.png)
呜呜呜. 为什么

**Comment by ItsFlicker** [comment]
@xANoyU 
最新版的Global可以直接过滤了 不用设置

**Comment by xANoyU** [comment]
> @xANoyU 最新版的Global可以直接过滤了 不用设置

不行诶, 从PRE11更新到刚发的PRE14, 依然可以直接发屏蔽词出来, 是还需要删改什么吗?
用的是Global.yml

**Comment by ItsFlicker** [comment]
> > @xANoyU 最新版的Global可以直接过滤了 不用设置
> 
> 不行诶, 从PRE11更新到刚发的PRE14, 依然可以直接发屏蔽词出来, 是还需要删改什么吗? 用的是Global.yml

提供下你用的服务端版本

**Comment by xANoyU** [comment]
> > > @xANoyU 最新版的Global可以直接过滤了 不用设置
> > 
> > 
> > 不行诶, 从PRE11更新到刚发的PRE14, 依然可以直接发屏蔽词出来, 是还需要删改什么吗? 用的是Global.yml
> 
> 提供下你用的服务端版本

Paper-1.12.2-1620

**Comment by ItsFlicker** [comment]
> > > > @xANoyU 最新版的Global可以直接过滤了 不用设置
> > > 
> > > 
> > > 不行诶, 从PRE11更新到刚发的PRE14, 依然可以直接发屏蔽词出来, 是还需要删改什么吗? 用的是Global.yml
> > 
> > 
> > 提供下你用的服务端版本
> 
> Paper-1.12.2-1620

1.12.2可能确有此问题 待修复

**Comment by xANoyU** [comment]
> > > > > @xANoyU 最新版的Global可以直接过滤了 不用设置
> > > > 
> > > > 
> > > > 不行诶, 从PRE11更新到刚发的PRE14, 依然可以直接发屏蔽词出来, 是还需要删改什么吗? 用的是Global.yml
> > > 
> > > 
> > > 提供下你用的服务端版本
> > 
> > 
> > Paper-1.12.2-1620
> 
> 1.12.2可能确有此问题 待修复

啊好的, 我还有一个疑问就是, Dragoncore(龙之核心)可以在1.12.2版本使用RGB颜色
例如 §#ed5a65渐§#ee6c76变§#ef7e87颜§#ef8f97色 这样的, 在MiaoChat上使用就可以正常显示
但是在TrChat上就不行, 会显示成这样子, 这个可以解决一下嘛
![image](https://user-images.githubusercontent.com/62326160/174491123-e59171d2-d005-4cc1-bf78-e3ace5007aed.png)

**Comment by ItsFlicker** [comment]
@xANoyU https://github.com/TrPlugins/TrChat/actions/runs/2526845622
可以直接过滤
也可以用Filter-Before-Sending

**Comment by ItsFlicker** [comment]
> 啊好的, 我还有一个疑问就是, Dragoncore(龙之核心)可以在1.12.2版本使用RGB颜色 例如 §#ed5a65渐§#ee6c76变§#ef7e87颜§#ef8f97色 这样的, 在MiaoChat上使用就可以正常显示 但是在TrChat上就不行, 会显示成这样子, 这个可以解决一下嘛 ![image](https://user-images.githubusercontent.com/62326160/174491123-e59171d2-d005-4cc1-bf78-e3ace5007aed.png)

这可能是因为低版本原版无法显示rgb颜色，为了保护客户端被自动向下采样了

之后会添加选项强制打开rgb

**Comment by xANoyU** [comment]
> > 啊好的, 我还有一个疑问就是, Dragoncore(龙之核心)可以在1.12.2版本使用RGB颜色 例如 §#ed5a65渐§#ee6c76变§#ef7e87颜§#ef8f97色 这样的, 在MiaoChat上使用就可以正常显示 但是在TrChat上就不行, 会显示成这样子, 这个可以解决一下嘛 ![image](https://user-images.githubusercontent.com/62326160/174491123-e59171d2-d005-4cc1-bf78-e3ace5007aed.png)
> 
> 这可能是因为低版本原版无法显示rgb颜色，为了保护客户端被自动向下采样了
> 
> 之后会添加选项强制打开rgb

想问下这个选项支持了吗😗😗😗
