### ISSUE TITLE
聊天信息跑到BC端上了。

### ISSUE THREAD

**Issue by cdcp998** [FlickerProjects/TrChat#119]
![ED9P{H0L `J1W~@HU$MM}40](https://user-images.githubusercontent.com/1726165/167262396-fa625a38-df2a-46be-999b-1ee248b33512.png)

**Comment by ItsFlicker** [comment]
正常吧

**Comment by ItsFlicker** [comment]
之后会有选项选择消息在子服还是BC端

**Comment by 157946a** [comment]
使用的是什么聊天,全局喊话还是Normal

**Comment by cdcp998** [comment]
> 使用的是什么聊天,全局喊话还是Normal

全局

**Comment by 157946a** [comment]
这个是正常的,不是什么问题,因为他喊话需要经过bc,miaochat那些具体也不知道是不是也这样

**Comment by cdcp998** [comment]
> 
因为我默认需要跨服喊话。那么能不能加2个选项。一个绑定服务器组，一个不显示到BC端上。

**Comment by cdcp998** [comment]
> 这个是没办法的,他是从触发全局喊话的子服发出一个数据包给bc,然后bc接收后还要发送到每个子服,同时还要保证其他插件不影响

那有点麻烦。因为我有几个子服。其他子服也可以收到信息。但我又不想让他们收到信息。只让2个子服收到信息。

**Comment by 157946a** [comment]
你是想要指定子服不能收到,还是不想让他出现在bc

**Comment by cdcp998** [comment]
> 你是想要指定子服不能收到,还是不想让他出现在bc

都想要。=。=只有指定子服能收到。和不出现在BC 子服留记录

**Comment by cdcp998** [comment]
Options 在那里呢。
