### ISSUE TITLE
展示功能崩服

### ISSUE THREAD

**Issue by Qlickly** [FlickerProjects/TrChat#120]
玩家打出大量展示符号，导致服务器崩溃。
![image](https://user-images.githubusercontent.com/104749184/167293366-e536c096-fc98-43a0-9482-8b7c782c33be.png)
![image](https://user-images.githubusercontent.com/104749184/167293378-b5700c49-137d-4a6b-9b01-ba32c145da62.png)
![Uploading image.png…]()

**Comment by 157946a** [comment]
尝试使用最新构建

**Comment by Qlickly** [comment]
使用最新的但是无法被加载，旧的就可以加载，核心版本1.12.2Paper

**Comment by 157946a** [comment]
删除function文件
