### ISSUE TITLE
TRchat无法和InteractiveChat插件一起使用

### ISSUE THREAD

**Issue by chengju6** [FlickerProjects/TrChat#121]
我最近把这2个插件装在一起的时候发现我没法用InteractiveChat展示背包和末影箱
显示是无法解析占位符 
![image](https://user-images.githubusercontent.com/62113680/167563875-88ae5a75-2553-4092-a4fb-a16a07507841.png)
那个插件的优先级我也都试过了也没用
我把trchat给卸了就可以正常使用

**Comment by 157946a** [comment]
你可以让作者添加一个末影箱展示
