### ISSUE TITLE
一些故障

### ISSUE THREAD

**Issue by hexadecimal233** [FlickerProjects/TrChat#126]
当essentialsX安装时，r命令无法回复
命令执行失败时，不会有任何提示

**Comment by 157946a** [comment]
并没有出现你说的该问题,说明插件版本和服务端核心版本

**Comment by hexadecimal233** [comment]
此问题是随机出现，并且使用核心是paper，插件版本最新，只要插件多于25个就会出错

**Comment by 157946a** [comment]
核心版本

**Comment by hexadecimal233** [comment]
paper-1.18.2-333

**Comment by hexadecimal233** [comment]
**只要**插件数量大于等于25个就会变成essentials的回复， _**无论插件是什么**_
是不是paper的异步加载吧他玩坏了
其他命令工作正常
