### ISSUE TITLE
发送信息重复

### ISSUE THREAD

**Issue by ghost** [FlickerProjects/TrChat#129]
![image](https://user-images.githubusercontent.com/68630033/168444595-d90e0eb4-4393-4f5a-a8f8-75af741e8619.png)
如图所示，一个原版，一个trchat，我这里有几个服务器，其他几个没问题，唯独这个服务器有
版本：Trchat-PRE-7

**Comment by ItsFlicker** [comment]
请提供插件列表

**Comment by ghost** [comment]
> 

![image](https://user-images.githubusercontent.com/68630033/168457884-b30e5d73-ad88-4586-9393-ca50dc9f2dcc.png)
大部分都是粘液科技附属

**Comment by ghost** [comment]
> 请提供插件列表

已提供

**Comment by 157946a** [comment]
把cmi config里面的ModifyChatFormat和ClickHoverMessage设置为关闭就好了

**Comment by ghost** [comment]
> 把cmi config里面的ModifyChatFormat和ClickHoverMessage设置为关闭就好了

谢谢你的帮助，但是这里我是默认关闭的，之前用trchat1.9时还正常

**Comment by 157946a** [comment]
删除插件,查看是否是插件冲突

**Comment by ghost** [comment]
更新版本至PRE9，恢复正常
