### ISSUE TITLE
PacketUtils 错误

### ISSUE THREAD

**Issue by Galaxy-VN** [FlickerProjects/TrChat#13]
当我启动插件时，我收到警告: https://paste.helpch.at/ifujiteser.md
当服务器中有一个活跃的玩家时，它会产生一个错误：https://paste.helpch.at/xefinaxoqo.rb
我正在使用 Java 16

**Comment by ItsFlicker** [comment]
Please test if the latest build fixed this bug

**Comment by Galaxy-VN** [comment]
its fixed eyy
