### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by YuanYuanOwO** [FlickerProjects/TrChat#130]
2.0.0-PRE-7与LibertyBans-1.0.2-SHAPSHOT同时安装会报以下错误

```
15.05 23:27:02 [Server] WARN Exception encountered when loading plugin: LibertyBans
15.05 23:27:02 [Server] INFO java.lang.IllegalStateException: *******************************************
15.05 23:27:02 [Server] INFO Plugin 'TrChat 2.0.0-PRE-7' has a critical bug. That plugin has shaded the library 'Kyori-Adventure' but did not relocate it, which will pose problems. 
15.05 23:27:02 [Server] INFO LibertyBans is not guaranteed to function if you do not fix this bug in Plugin 'TrChat 2.0.0-PRE-7'
15.05 23:27:02 [Server] INFO Contact the author of this plugin and tell them to relocate their dependencies. Unrelocated class detected was net.kyori.adventure.audience.Audience
15.05 23:27:02 [Server] INFO Note for advanced users: Understanding the consequences, you can disable this check by setting the system property libertybans.relocationbug.disablecheck to 'true'
15.05 23:27:02 [Server] INFO *******************************************
15.05 23:27:02 [Server] INFO at space.arim.libertybans.bootstrap.LibertyBansLauncher.warnRelocation(LibertyBansLauncher.java:90) ~[?:?]
15.05 23:27:02 [Server] INFO at space.arim .libertybans.bootstrap.LibertyBansLauncher.determineNeededDependencies(LibertyBansLauncher.java:108) ~[?:?]
15.05 23:27:02 [Server] INFO at space.arim.libertybans.bootstrap.LibertyBansLauncher.attemptLaunch(LibertyBansLauncher.java:136) ~[?:?]
15.05 23:27:02 [Server] INFO at space.arim.libertybans.bootstrap.LibertyBansLauncher.attemptLaunch(LibertyBansLauncher.java:124) ~[?:?]
15.05 23:27:02 [Server] INFO at space.arim.libertybans.env.bungee.BaseWrapper$Creator.create(BaseWrapper.java:71) ~[?:?]
15.05 23:27:02 [Server] INFO at space.arim.libertybans.env.bungee.BungeePlugin.onEnable(BungeePlugin.java:39) ~[?:?]
15.05 23:27:02 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
15.05 23:27:02 [Server] INFO at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
15.05 23:27:02 [Server] INFO at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
15.05 23:27:02 [Server] INFO at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
```

**Comment by hexadecimal233** [comment]
他好像是注册了一些喊话的命令比如say mute什么的和这个冲突了
最近作者修bug好像很不积极的样子

**Comment by ItsFlicker** [comment]
是个依赖重定向问题
可能无法修复
可以先根据提示禁用检查(you can disable this check by setting the system property libertybans.relocationbug.disablecheck to 'true')

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月15日(周日) 晚上11:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [FlickerProjects/TrChat] 报错 (Issue #130)



 
2.0.0-PRE-7与LibertyBans-1.0.2-SHAPSHOT同时安装会报以下错误
 15.05 23:27:02 [Server] WARN Exception encountered when loading plugin: LibertyBans 15.05 23:27:02 [Server] INFO java.lang.IllegalStateException: ******************************************* 15.05 23:27:02 [Server] INFO Plugin 'TrChat 2.0.0-PRE-7' has a critical bug. That plugin has shaded the library 'Kyori-Adventure' but did not relocate it, which will pose problems.  15.05 23:27:02 [Server] INFO LibertyBans is not guaranteed to function if you do not fix this bug in Plugin 'TrChat 2.0.0-PRE-7' 15.05 23:27:02 [Server] INFO Contact the author of this plugin and tell them to relocate their dependencies. Unrelocated class detected was net.kyori.adventure.audience.Audience 15.05 23:27:02 [Server] INFO Note for advanced users: Understanding the consequences,  15.05 23:27:02 [Server] INFO ******************************************* 15.05 23:27:02 [Server] INFO at space.arim.libertybans.bootstrap.LibertyBansLauncher.warnRelocation(LibertyBansLauncher.java:90) ~[?:?] 15.05 23:27:02 [Server] INFO at space.arim .libertybans.bootstrap.LibertyBansLauncher.determineNeededDependencies(LibertyBansLauncher.java:108) ~[?:?] 15.05 23:27:02 [Server] INFO at space.arim.libertybans.bootstrap.LibertyBansLauncher.attemptLaunch(LibertyBansLauncher.java:136) ~[?:?] 15.05 23:27:02 [Server] INFO at space.arim.libertybans.bootstrap.LibertyBansLauncher.attemptLaunch(LibertyBansLauncher.java:124) ~[?:?] 15.05 23:27:02 [Server] INFO at space.arim.libertybans.env.bungee.BaseWrapper$Creator.create(BaseWrapper.java:71) ~[?:?] 15.05 23:27:02 [Server] INFO at space.arim.libertybans.env.bungee.BungeePlugin.onEnable(BungeePlugin.java:39) ~[?:?] 15.05 23:27:02 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486] 15.05 23:27:02 [Server] INFO at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486] 15.05 23:27:02 [Server] INFO at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486] 15.05 23:27:02 [Server] INFO at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]

**Comment by 157946a** [comment]
> 他好像是注册了一些喊话的命令比如say mute什么的和这个冲突了 最近作者修bug好像很不积极的样子

你不上学你来修

**Comment by hexadecimal233** [comment]
我用其他插件也有这个bug，应该不是问题

**Comment by ThebestkillerTBK** [comment]
我用其他插件也有这个bug，应该不是问题

**Comment by ItsFlicker** [comment]
使用shaded版本
