### ISSUE TITLE
开启proxy无法发送消息

### ISSUE THREAD

**Issue by LatosProject** [FlickerProjects/TrChat#140]
使用 VELOCITY，trchat pre10
子端spigot已开启bc
开启proxy无法玩家发送消息 没有任何提示
子端和群组端也无提示

**Comment by hexadecimal233** [comment]
我这里是执行了reload后不显示消息，要重进再会显示

**Comment by ItsFlicker** [comment]
> 我这里是执行了reload后不显示消息，要重进再会显示

最新版吗

**Comment by hexadecimal233** [comment]
是的

**Comment by ItsFlicker** [comment]
> 是的

https://github.com/TrPlugins/TrChat/actions/runs/2529335314 修复
