### ISSUE TITLE
玩家进入游戏后台偶尔会刷报错

### ISSUE THREAD

**Issue by SueFox** [FlickerProjects/TrChat#145]
[报错.log](https://github.com/TrPlugins/TrChat/files/8977461/default.log)
[插件加载时的报错.log](https://github.com/TrPlugins/TrChat/files/8977570/default.log)

服务器是在bc环境下运行的
(用了一下TrMenu的信息粘贴awa)
TrMenu Dump Information (Date: 2022-06-24 23:54:03)

| Server OS: Windows Server 2022 amd64 10.0
| Server software: git-Paper-1620 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 11.0.15.11

| TrChat - 2.0.0-PRE-15
Installed Plugins: 
· ArmorSwitcher - 1.2 (0 KB)
· BetterChairs - 1.5.1 (0 KB)
· CMILib - 1.2.0.2 (0 KB)
· CommandWhitelist - 1.2.3 (0 KB)
· CrackShot - 0.98.11 (0 KB)
· CrackShotPlus - 1.106 (0 KB)
· FastAsyncWorldEdit - 21.03.26-b67f782-1287-22.3.10 (0 KB)
· Hitmarkers - Build 16 (0 KB)
· IronElevators - 1.6 (0 KB)
· Join-Leave - 2.2 (0 KB)
· LuckPerms - 5.4.30 (0 KB)
· MBedwars - 5.0.11 (0 KB)
· Multiverse-Core - 2.6.0-b738 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerPoints - 3.2.4 (0 KB)
· PremiumVanish - 2.7.14 (0 KB)
· ProtocolLib - 5.0.0-SNAPSHOT-b556 (0 KB)
· SelectionVisualizer - 3.2.0.0 (0 KB)
· SimpleCombatTag - 1.1 (0 KB)
· TrMenu - 3.1.11 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VoidWorld - 1.0 (0 KB)
· Vulcan - 2.6.6-HOTFIX (0 KB)
· WorldChangeScreenRemover - 1.0.18 (0 KB)
· WorldEdit - 6.1.7;dd00bb1 (0 KB)
· XConomy - 2.18.12 (0 KB)
· spark - 1.9.13 (0 KB)

**Comment by ItsFlicker** [comment]
> 插件加载时的报错.log

重新生成function.yml

**Comment by ItsFlicker** [comment]
> 报错.log

https://github.com/TrPlugins/TrChat/actions/runs/2560479915 可能解决

**Comment by SueFox** [comment]
> > 插件加载时的报错.log
> 
> 重新生成function.yml

甚至连TrMenu的报错也解决了

**Comment by SueFox** [comment]
> > 报错.log
> 
> https://github.com/TrPlugins/TrChat/actions/runs/2560479915 可能解决

经过我的高强度反复折磨应该是解决了qwq
