### ISSUE TITLE
1.19 purpur端 ia插件emoji显示问题

### ISSUE THREAD

**Issue by AntsandIce** [FlickerProjects/TrChat#152]
当我输入itemsadder的emoji功能
不管是ia的/emoji 还是ia的:emoji: 或是字体替换图片时 
总会多显示 后台§f
游戏 显示 ![image](https://user-images.githubusercontent.com/52115447/176906684-778c200b-1228-483c-8b7a-031127915999.png)
但我在聊天框 图片(emoji前输入任意两个个字符)就会消失

删除Trchat则可正常显示..

**Comment by ItsFlicker** [comment]
最新版未复现
https://github.com/TrPlugins/TrChat/actions/runs/2613323222
如果还有这种情况请提供频道文件
