### ISSUE TITLE
[1.19]您收到了乱序的聊天数据包

### ISSUE THREAD

**Issue by ghost** [FlickerProjects/TrChat#153]
![image](https://user-images.githubusercontent.com/78008410/176989349-b817ab72-666f-470e-965a-c8d0e9a8c1af.png)
BC：velocity-3.1.2-SNAPSHOT-158
子服务器: Purpur - 1.19

插件版本:
TrChat-2.0.0-PRE-19

描述:
经常出现乱序数据包，非1.19不会出问题
而且后台无报错 只有前台会把人直接踢出去

**Comment by ItsFlicker** [comment]
尝试在settings.yml中添加
```yaml
Options:
  Send-Message-Method: SYSTEM
```

**Comment by Dreeam-qwq** [comment]
> 尝试在settings.yml中添加
> 
> ```yaml
> Options:
>   Send-Message-Method: SYSTEM
> ```

貌似还是有几率被踢出

**Comment by ghost** [comment]
> 尝试在settings.yml中添加
> 
> ```yaml
> Options:
>   Send-Message-Method: SYSTEM
> ```

还是有

**Comment by ItsFlicker** [comment]
尝试这个https://github.com/TrPlugins/TrChat/actions/runs/2613323222

**Comment by ghost** [comment]
使用purpur 并且调整kick out order of chat 为 false
请升级最新dev版本即可
