### ISSUE TITLE
/ignore 在全局频道[Global 或 Proxy: true]上似乎不工作

### ISSUE THREAD

**Issue by xiangxiangxiong9** [FlickerProjects/TrChat#155]
emm...怎么说呢...
如果频道是Normal[即Proxy: false]时ignore能正常工作
但一旦频道为Global[即Proxy: true]ignore就不工作了...

#

断点[雾]
https://github.com/TrPlugins/TrChat/blob/03c172b32d0ecdfa9d144ccfd60c805f3e3a3873/project/implementation-bukkit/src/main/kotlin/me/arasple/mc/trchat/module/internal/BukkitComponentManager.kt#L85
\+ commandSender.sendMessage(identity, Component.text(identity.uuid().toString()), MessageType.CHAT)
proxy: false 时输出: <玩家的UUID>
proxy: true 时输出: 00000000-0000-0000-0000-000000000000

**Comment by ItsFlicker** [comment]
Fixed in https://github.com/TrPlugins/TrChat/actions/runs/2613323222

**Comment by xiangxiangxiong9** [comment]
问题似乎解决了..

**Comment by xiangxiangxiong9** [comment]
问题似乎解决了
#
emm...能把ignore后的结果加个提示吗,,执行后不知道是屏蔽了还是解除屏蔽了 0.0
或者执行ignore不带玩家名提示已屏蔽的玩家列表
