### ISSUE TITLE
[Solved] 无法支持龙核颜色

### ISSUE THREAD

**Issue by xANoyU** [FlickerProjects/TrChat#160]
https://github.com/TrPlugins/TrChat/issues/118#issuecomment-1160002545
之前在一篇Issues里提到了这个 因为非常想要所以想询问一下这个选项还会更新出来吗

**Comment by ItsFlicker** [comment]
如果使用不跨服频道能否让RGB正常呢

**Comment by xANoyU** [comment]
有试过 但是不行

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ItsFlicker ***@***.***>
发送时间: Friday, July 15, 2022 5:25:54 PM
收件人: TrPlugins/TrChat ***@***.***>
抄送: xANoyU ***@***.***>; Author ***@***.***>
主题: Re: [TrPlugins/TrChat] 关于RGB颜色问题 (Issue #160)


如果使用不跨服频道能否让RGB正常呢

―

**Comment by ItsFlicker** [comment]
使用https://github.com/TrPlugins/TrChat/actions/runs/2676524348 
在settings.yml中打开Force-Hex-Color

**Comment by xANoyU** [comment]
> 使用https://github.com/TrPlugins/TrChat/actions/runs/2676524348 在settings.yml中打开Force-Hex-Color

不行诶，不能正常显示
![QQ截图20220715200951](https://user-images.githubusercontent.com/62326160/179220239-a1b2082e-bbc5-45d5-817d-b01d7e407e36.png)

**Comment by xANoyU** [comment]
> 使用https://github.com/TrPlugins/TrChat/actions/runs/2676524348 在settings.yml中打开Force-Hex-Color

呜呜球球了可以抢救一下吗

**Comment by ItsFlicker** [comment]
PRE-30 可能修复

**Comment by xANoyU** [comment]
> PRE-30 可能修复

测试了一下，添加RGB后发不出消息（后台没有游戏内也没有）
![image](https://user-images.githubusercontent.com/62326160/187023957-5a061df5-9466-4c72-9ada-1281aa5f1124.png)

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/9451980664
