### ISSUE TITLE
Chat filter problem

### ISSUE THREAD

**Issue by SnowCutieOwO** [FlickerProjects/TrChat#162]
**描述 (Description)** 本插件会将其他插件发送的消息一并过滤。

**建议 (Suggestion)** 优化插件消息过滤功能，例如添加允许不过滤的插件白名单。

**Comment by ItsFlicker** [comment]
插件采用改发包的方式过滤，有时候无法准确判断是否为玩家发出（adventure库的锅），也无法判断是哪个插件的消息
如果不想让插件过滤其他信息，可以参考 #122
