### ISSUE TITLE
禁言指令问题

### ISSUE THREAD

**Issue by konakona-code** [FlickerProjects/TrChat#163]
我在后台使用指令：trchat:mute _konakona(player) <time> <reason>以对玩家进行禁言，但后台给我的反馈是：[03:27:27 INFO]: [TrChat] You muted _konakona for 999d.Reason: null
现在我无法对该玩家解除禁言，我已经尝试了trchat:unmute/pardon/unmute等方式
请问能否在不进入数据库的情况下，使用指令对该惩罚撤回或清除
感谢！

**Comment by ItsFlicker** [comment]
使用/mute (player) --cancel
