### ISSUE TITLE
游戏内无法用任何指令

### ISSUE THREAD

**Issue by linsnowmm** [FlickerProjects/TrChat#164]
![LQ_$4S4)NN{1S7F3N~E8MBO](https://user-images.githubusercontent.com/97744559/182125014-156837ee-35db-4f73-9498-c56fb789f241.png)
核心:paper.1.19.1-97
插件版本：TrChat-2.0.0-PRE-18-shaded

**Comment by ItsFlicker** [comment]
使用最新构建即可
