### ISSUE TITLE
关于聊天频道的问题

### ISSUE THREAD

**Issue by lijinhong11** [FlickerProjects/TrChat#176]
有2个频道，第一个频道不能接收来自第2个频道的信息，而第二个频道不能接收第1个频道的信息，这个能不能添加上去？如果有了，那怎么做呢？

**Comment by ItsFlicker** [comment]
频道文件Options中把Auto-Join改为false

**Comment by lijinhong11** [comment]
> 频道文件Options中把Auto-Join改为false

不是，我说不能互相接收频道的聊天信息

**Comment by ItsFlicker** [comment]
Auto-Join改为false后只能加入其中一个频道，就不能接受另一个频道的信息了

**Comment by lijinhong11** [comment]
> Auto-Join改为false后只能加入其中一个频道，就不能接受另一个频道的信息了

那能不能整个自动退出其他频道的

**Comment by ItsFlicker** [comment]
所有频道都是Auto-Join: false 就自动退出了

**Comment by lijinhong11** [comment]
那如果从一个正常聊天频道(Auto-Join: true)切换过来呢

**Comment by ItsFlicker** [comment]
接受正常频道消息 发送在新频道内
