### ISSUE TITLE
阿里云 Maven 依赖缺失导致启动阶段访问数据库报错

### ISSUE THREAD

**Issue by DreamUniverse843** [FlickerProjects/TrChat#179]
使用的是最新的构建版本（PRE-27）。
服务端核心：CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

https://pastebin.ubuntu.com/p/7Tj4Cvshw9/

**Comment by DreamUniverse843** [comment]
刚才在 1.16.5 版本的服务端测试，同样无法拉取数据库依赖。

**Comment by SueFox** [comment]
> 刚才在 1.16.5 版本的服务端测试，同样无法拉取数据库依赖。

我也是awa。。。。。1.19的purpur，一直卡在下载这个依赖

**Comment by SueFox** [comment]
> 刚才在 1.16.5 版本的服务端测试，同样无法拉取数据库依赖。

wc我刚发玩就下载好了？？？？？？？？？？？？？？？
