### ISSUE TITLE
16进制颜色代码问题

### ISSUE THREAD

**Issue by GarfieldMeow** [FlickerProjects/TrChat#19]
在formats配置中的  hover: |- 一栏内，输入16进制颜色 在游戏中会显示为白色
        text: '&{#00FF7F}Test'  <----正常显示
        hover: |-
          &{#00FF7F}Test <----游戏内为白色
(如果能支持一下原版的 {#XXXXX} 格式就好了，大部分支持16进制颜色的插件为 {#XXXXX} 将变量填写进Trchat内就无法识别了，Thanks♪(･ω･)ﾉ)

**Comment by ItsFlicker** [comment]
1. Spigot目前不支持hover text的十六进制颜色，无法修复
2. 最新构建已支持{#XXXXX}

**Comment by GarfieldMeow** [comment]
> 1. 水龙头当前不支持悬停文字的十六进制颜色，无法修复
> 2. 最新构建已支持{#XXXXX}

谢谢
