### ISSUE TITLE
pre32在spigot 1.12.2上发出的文字显示有问题

### ISSUE THREAD

**Issue by chencu5958** [FlickerProjects/TrChat#190]
如图所示，但后台无报错，查看trchat聊天日志是显示的是正常内容
![F8{8N(QE V1}TNB@GGS7 1O](https://user-images.githubusercontent.com/82279230/188331184-5a1dfb98-1872-4419-9e63-7463abde0ccf.png)
插件列表如下，所有配置均为默认配置，更换ESSX后依然是该情况，所有插件版本均为最新版（仅保留papi插件和trchat还是存在该问题）
![N}UKZL1QTGEO{_$C8 R $Y4](https://user-images.githubusercontent.com/82279230/188331209-56f7a60f-8c68-438f-808c-fd2b2ab4e83f.png)
![G{U9A$PV93H5V)(7}XQLE)S](https://user-images.githubusercontent.com/82279230/188331373-f675b74b-db6a-457f-98a6-8f2282381190.png)

服务端文件链接放这里了
链接：https://pan.baidu.com/s/1nbu2AmuRDGZwrw0qJbyGBQ?pwd=0nz6 
提取码：0nz6

运行环境
Windows Server 2019
JDK11 v11.0.15

**Comment by chencu5958** [comment]
在给别的服务器升级pre30时就已遇到类似问题，不过发出的文字是会被加上black前缀，类似这样 [world] player: black发出的内容（我这边测试了是只对一部分ID有效，比如我用的xiao_a_s），然后更新pre31的black字样解决了，但遇到了issue里反馈的问题，更换pre32后依然还是有问题

**Comment by Maxwellboys** [comment]
发你下你的配置吧，我今天刚好解决了

**Comment by chencu5958** [comment]
> 发你下你的配置吧，我今天刚好解决了

pre32上复现的全是基于默认配置无修改，包括服务端配置文件也是（参考我上传的那个服务端压缩包就行了），pre30上因为我的服务端上面跑的插件过多没办法直接排障，pre31同理
