### ISSUE TITLE
[问题]: 屏蔽词系统没有生效

### ISSUE THREAD

**Issue by DreamUniverse843** [FlickerProjects/TrChat#198]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1. 正常初始化 TrChat，placeholderAPI 上安装必要的依赖；
2. 在 filter.yml 中启用全部的过滤配置，重启服务端，无效；
3. 在所有频道的 Options 上添加 Filter-Before-Sending: true，重启服务端，过滤依然无效；
4.  参考了 Issues #122，尝试将 filter.yml 中的 Chat 字段设置为 False，在频道中添加下列字段：
```
Events:
 Process: |-
    filter get &message
```
但依然无效。
无论是云端词库还是本地词库均无法使用。
已经没有思路如何解决问题，有劳开发者了！

### 配置文件

```YAML
Global.yml:https://pastebin.ubuntu.com/p/MZr9cWJqH7/
Normal.yml:https://pastebin.ubuntu.com/p/FZNHNkwt4c/
Settings.yml:https://pastebin.ubuntu.com/p/d6j78d2WmP/
filter.yml:https://pastebin.ubuntu.com/p/wJ5HBDB2cG/
```

### 日志

无报错，只是屏蔽词没屏蔽。
![image](https://user-images.githubusercontent.com/53889721/194803902-328cda5d-f340-477e-8ba8-e7deafa9d163.png)
以图为例，"f*ck"和"xxs"均在本地词库和云端词库存在，但屏蔽未生效。

### 服务器环境

服务器版本:
CraftBukkit version 3096a-Spigot-9fb885e-af1a232 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
插件列表:
Plugins (4): LuckPerms, Vault, PlaceholderAPI, TrChat

**Comment by DreamUniverse843** [comment]
补遗：我发言的时候并没有给予 trchat.bypass.filter 权限。

**Comment by ItsFlicker** [comment]
最新版应该已修复
