### ISSUE TITLE
Hex color error on hover

### ISSUE THREAD

**Issue by LeAnhTuan0810** [FlickerProjects/TrChat#20]
When I use hex color in hover(chat format) it shows different color, not hex color
I use &{#FFC125} it returns purple
https://sourceb.in/Auz7zCKOFb

**Comment by ItsFlicker** [comment]
It seems that spigot doesn't support hex color in hover text.
So this cannot be fixed for the time being.

**Comment by Aira-Sakuranomiya** [comment]
https://github.com/lintx/Minecraft-Plugin-YinwuChat/tree/v2.11.1
This plugin can do this...

**Comment by ItsFlicker** [comment]
Try https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1

**Comment by Aira-Sakuranomiya** [comment]
![QQ截图20220328193441](https://user-images.githubusercontent.com/45261195/160389657-dbf87d7e-5b98-4b4f-a7ce-c44b3bc2895b.png)
plugin doesn't work
newest Paper 1.18.2

**Comment by Aira-Sakuranomiya** [comment]
旧版迁移过来是必须要重写配置吗

**Comment by ItsFlicker** [comment]
2.0.0-PRE-2 fixed
