### ISSUE TITLE
[问题]: ORIGIN-NAME: false 不显示修改过的物品名字

### ISSUE THREAD

**Issue by MuMuMuCODE** [FlickerProjects/TrChat#206]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

无论设置 ORIGIN-NAME true 还是false 都是显示物品原本的名字

### 配置文件

```YAML
无
```

### 服务器环境

服务器版本:
purpur 1.18.2

**Comment by ItsFlicker** [comment]
Fixed in RC-4
