### ISSUE TITLE
[问题]: 不支持1.19.3

### ISSUE THREAD

**Issue by CuteLittleSky** [FlickerProjects/TrChat#208]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

在1.19.2正常运行,1.19.3不支持

### 配置文件

```YAML
null
```

### 服务器环境

服务器版本:
Velocity + Paper 1.19.3
插件列表:
...

**Comment by ItsFlicker** [comment]
等待TabooLib支持1.19.3

**Comment by CuteLittleSky** [comment]
> 等待TabooLib支持1.19.3

支持了 )

**Comment by CuteLittleSky** [comment]
测试可以正常使用 感谢 )
