### ISSUE TITLE
如何在某个单服禁用跨服聊天

### ISSUE THREAD

**Issue by CuteLittleSky** [FlickerProjects/TrChat#210]
我想在某个单服安装Trchat,但不想在该服务器使用跨服聊天功能(也就是让其他服务器的跨服聊天消息不能被这个单服接收)
尝试将settings中的proxy改为NONE,但单服仍然能接受到跨服聊天消息,求解答

谢谢 )

**Comment by ItsFlicker** [comment]
在其他服的设置里写Ports参数, 排除这个服

**Comment by ItsFlicker** [comment]
https://trchat.plugindoc.cn/liao-tian-pin-dao/configuration/options

**Comment by CuteLittleSky** [comment]
感谢大佬 :)
解决了 ₍˄·͈༝·͈˄*₎◞ ̑̑
