### ISSUE TITLE
[功能请求]在1.16+的服务器上实现自定义字体

### ISSUE THREAD

**Issue by Pectix** [FlickerProjects/TrChat#214]
# 简述
如题，1.16+的JSON文本格式中新增了font属性的自定义，如font属性为"\<namespace\>:fontname"将匹配资源包内assets/\<namespace\>/fontname.json的字体内容，但是对于插件服务器来说，无法在所有地方(如插件配置文件内)正常使用JSON格式文本，所以希望添加一个tag来实现自定义字体的功能。

# 其他插件
InteractiveChat插件的配置文件中已有Settings.FormattingTags.AllowFontTags配置项用来开启"[font=uniform]"格式的字体显示，但该插件的功能只能在聊天栏中实现，无法监听如title lore actionbar 告示牌中的内容。

# 举例实现
TrChat已存在一些tag，如<g:>渐变色、<r:>彩虹色等等，为了tag格式的统一，我建议使用\<font:\>/<f:>来实现自定义字体。

# 补充说明
实际上，\<font:\>标签的优先级应与原版的格式代码相同，例如&l会在已更改颜色的情况下加粗，而&l&a中作为颜色代码则会重置格式代码，实际上与&a无异。
同样，&a\<font:uniform\>应实现"改变颜色后改变字体"，而\<font:uniform\>&a应实现"因颜色代码而重置字体(font:default)"的功能

* 主流插件大部分还未实现此功能，此功能在自定义资源包的服务器上大有用处，望采纳！

**Comment by Pectix** [comment]
补充一下，由于我的聊天格式中自带渐变文本，可能与InteractiveChat的标签产生冲突，实际上InteractiveChat已经实现了title subtitle actionbar 和聊天页面中的内容更改，但经实测如告示牌、lore、物品名称等地方InteractiveChat还未实现字体功能。同样请求实现的是TrChat支持在物品名称、lore等界面使用\<g:\>、\<r:\>。

**Comment by ItsFlicker** [comment]
可能使用 https://github.com/TrPlugins/TrChat/issues/92 实现

**Comment by ItsFlicker** [comment]
实测在只安装TrChat和papi的情况下可以改变字体
但放在生产环境中无法使用
可能为其他插件也会监听改变铁砧/告示牌

**Comment by ItsFlicker** [comment]
使用SimpleComponent实现
