### ISSUE TITLE
[疑问] trchat能否实现跨代理端发言之类的？

### ISSUE THREAD

**Issue by chencu5958** [FlickerProjects/TrChat#218]
这个问题应该挺特别的吧，就是分别搭建A和B两个代理端，然后都指向到两个同样的服务器，目前遇到的问题是，在不同的代理端但在同一个子服上能收发聊天信息（仅能正常收发，像tell等都无法正常使用），若两个玩家在不同的代理端&子服上则会遇到无法使用喊话等功能的情况，反正就是有涉及到跨服的就不能正常收发工作了，测试时使用的是最新版trchat，配置无修改，代理端用的flamecord

**Comment by chencu5958** [comment]
以及trchat里新添加上有关redis数据库部分的配置文件如何使用？在文档站上并未发现对这段部分的文档说明，还有function.yml中的Image-Show功能怎么使用？反正就是新加入的内容如何使用之类的相关说明好像还未在文档站上同步更新

**Comment by ItsFlicker** [comment]
redis能跨代理端
等更新下文档

**Comment by chencu5958** [comment]
> redis能跨代理端 等更新下文档

好的，了解了，刚刚已经试着通过里面的redis配置实现了跨代理端聊天，但依然还是搞不明白里面channel和subscribe这两个配置项到底该怎么配置，然后实测，trchat也可以兼容multipaper这类服务端，不过得开启跨代理端转发加针对性的端口转发等，要不然multipaper实例是没办法正常收发消息，但目前国内用multipaper做服的应该不多，但也成功实测了trchat能在上面正常工作，后面有人反馈类似的问题的话就有解决方法了

**Comment by chencu5958** [comment]
> redis能跨代理端 等更新下文档

对了，可以问问就是trchat会提供papi变量用来填充吗？比如用于区分目前所在的频道的变量等，就比如VentureChat上面提供的变量
