### ISSUE TITLE
[问题]: trchat不兼容EZColors

### ISSUE THREAD

**Issue by ghost** [FlickerProjects/TrChat#222]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.安装EZColors
2.安装trchat
3.EZColors无法控制聊天颜色

### 配置文件

```YAML
略
```

### 服务器环境

服务器版本:
purpur-1.19.3
插件列表:
EZColors and trchat

**Comment by XiaoJie-150** [comment]
settings.yml的ChatEvent-Hooks加上尝试

**Comment by ItsFlicker** [comment]
尝试将EZColors中的ChatListener改为HIGH

**Comment by ItsFlicker** [comment]
PRE-37解决
