### ISSUE TITLE
[功能请求]死亡信息？

### ISSUE THREAD

**Issue by SAVEVI** [FlickerProjects/TrChat#223]
：））））））
貌似弃坑了一个类似的。不是很了解。因为今天我才突然意识到这个死亡信息。
我很苦恼。
因为那上面的插件要么不支持更多附魔。要么没有悬浮窗。还有就是不支持中文。
https://www.spigotmc.org/resources/deathmessages.100244/
https://www.spigotmc.org/resources/deathmessages.3789/
不求自定义信息qwq只求能有个悬浮窗（击杀者，被击杀者，手持武器
可能是我能力不够找不到替代品：（（（
本人完全萌新：（（
如有冲撞或者无头无脑的话请直接无视：：：：
恳求作者大大：））（小心翼翼

**Comment by XiaoJie-150** [comment]
这不属于chat范围吧

**Comment by SAVEVI** [comment]
是的，打扰了。
但这就像我一开始找chat插件一样。我想在%item%上显示我的自定义附魔（eco更多附魔等等
我选择了trchat。因为它支持这些！
但是悲伤的是我还没有找到能够同时支持mm插件和自定义附魔插件的死亡信息显示插件：：（（
打扰了XD
我会再仔细一点的。
我已经设想了两种解决方案。
感谢你的回复。XD

**Comment by XiaoJie-150** [comment]
我推荐你去bbs用金粒提问,数量够多就会有人来,一个人不如一群人

**Comment by SAVEVI** [comment]
好的：）））））））

**Comment by ItsFlicker** [comment]
不会在TrChat中实现
以后可能会出类似EnchantDeath的插件

**Comment by SAVEVI** [comment]
谢谢：）））
