### ISSUE TITLE
[问题]: 不支持跨服命令屏蔽玩家

### ISSUE THREAD

**Issue by fyxrim** [FlickerProjects/TrChat#228]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

不支持跨服命令屏蔽玩家

A服 player1 想屏蔽player2  命令屏蔽不了

B服 player2

### 配置文件

```YAML
默认配置
```

### 服务器环境

服务器版本:
...
插件列表:
...

**Comment by ItsFlicker** [comment]
是否连接MySQL数据库?
