### ISSUE TITLE
DiscordSRV無法讀取訊息

### ISSUE THREAD

**Issue by 1636578433** [FlickerProjects/TrChat#23]
我的服務器主要玩家都是來自海外,所以都是透過Discord進行溝通,希望能修復DiscordSRV(https://www.spigotmc.org/resources/discordsrv.18494/)插件不能讀取聊天欄訊息的問題

**Comment by ItsFlicker** [comment]
请尝试[最新构建](https://github.com/FlickerProjects/TrChat/actions/runs/1297626252)是否修复

**Comment by 1636578433** [comment]
用你這個构建還是不可以

**Comment by ItsFlicker** [comment]
[试试这个](https://github.com/FlickerProjects/TrChat/actions/runs/1299741661)

**Comment by 1636578433** [comment]
好像還是讀不了訊息

**Comment by 1636578433** [comment]
![name](https://user-images.githubusercontent.com/26202461/135892787-6bcbd252-d207-4560-a9c1-fcff3e5df4c9.PNG)
DiscordSRV配置文件中可以設置服務器裡面聊天頻道的名字,trchat是不是也有對應的名字?

**Comment by ItsFlicker** [comment]
最新构建还是无法读取吗
尝试使用DiscordSRV的debug功能看看有什么消息

**Comment by 1636578433** [comment]
[INFO] ....[Async Chat Thread - #59] [ 管理員 ] HAPPYHIN: .

[INFO] ....[Craft Scheduler Thread - 735] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: global

[INFO] ....[Craft Scheduler Thread - 736] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: global

[INFO] ....[Craft Scheduler Thread - 735] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User HAPPYHIN sent a message but it was not delivered to Discord because the chat event was canceled

[INFO] ....[Craft Scheduler Thread - 736] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User HAPPYHIN sent a message but it was not delivered to Discord because the chat event was canceled

[INFO] ....[Server thread] Ghosts_Daniel blew up

[INFO] ....[Craft Scheduler Thread - 721] [DiscordSRV] [UNCATEGORIZED DEBUG] Constructed avatar url: https://crafatar.com/avatars/cd82b4d08c754a55baa717dc33ebb6fb.png?size=128&overlay#bd63fa2c1915e90863a9c19142d4927d527b52af3284b54e2de9dd186d4795f5 from https://crafatar.com/avatars/{uuid-nodashes}.png?size={size}&overlay#{texture}

[INFO] ....[Craft Scheduler Thread - 721] [DiscordSRV] [UNCATEGORIZED DEBUG] Avatar url is for uuid: cd82b4d0-8c75-4a55-baa7-17dc33ebb6fb. The texture is: bd63fa2c1915e90863a9c19142d4927d527b52af3284b54e2de9dd186d4795f5

[INFO] ....[Async Chat Thread - #59] [ 玩家 ] Ghosts_Daniel: W T F

[INFO] ....[Craft Scheduler Thread - 721] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: global

[INFO] ....[Craft Scheduler Thread - 735] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: global

[INFO] ....[Craft Scheduler Thread - 721] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User Ghosts_Daniel sent a message but it was not delivered to Discord because the chat event was canceled

[INFO] ....[Craft Scheduler Thread - 735] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User Ghosts_Daniel sent a message but it was not delivered to Discord because the chat event was canceled

[INFO] ....[Async Chat Thread - #59] [ 玩家 ] Ghosts_Daniel: 直接一堆臭蟲殺過來

[INFO] ....[Craft Scheduler Thread - 735] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: global

[INFO] ....[Craft Scheduler Thread - 740] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: global

[INFO] ....[Craft Scheduler Thread - 735] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User Ghosts_Daniel sent a message but it was not delivered to Discord because the chat event was canceled

[INFO] ....[Craft Scheduler Thread - 740] [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User Ghosts_Daniel sent a message but it was not delivered to Discord because the chat event was canceled

**Comment by ItsFlicker** [comment]
已定位问题
使用最新构建即可

**Comment by 1636578433** [comment]
現在是解決了伺服器訊息不出現在discord的問題,可是現在由discord發送的訊息伺服器卻接收不到了
開了debug也只出現了這一條
[INFO] ....[JDA MainWS-ReadThread] [DiscordSRV] Chat: [Discord | BOSS] HIN > test

**Comment by 1636578433** [comment]
問題解決了,感謝!
