### ISSUE TITLE
能否设置只允许私聊？

### ISSUE THREAD

**Issue by HansOffice** [FlickerProjects/TrChat#231]
我想知道trchat能否设置玩家只允许使用私聊功能，如果不能的话那是否支持单独世界频道呢？
比如说主世界聊天只有主世界玩家可以看到，其他世界玩家无法看到

**Comment by ItsFlicker** [comment]
不给玩家常规说话的频道权限就是只允许私聊
单独世界频道文档有讲

**Comment by HansOffice** [comment]
单独世界频道是指Target: ALL的ALL改成世界名吗？
