### ISSUE TITLE
[问题]: 与QuickShop-Hikari的相关问题

### ISSUE THREAD

**Issue by YuanYuanOwO** [FlickerProjects/TrChat#236]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.摆放一个箱子，并创建商店，左键输入物品价格后，价格会显示在聊天栏，但商店创建成功
2.与商店交易时，所需交易的数量也同样会显示在聊天栏中
![qsbug](https://user-images.githubusercontent.com/81153017/220358223-bbfc56b3-ba34-46c5-a9ee-dc9afdf2bcc7.png)

### 配置文件

```YAML
无，默认RC-8配置文件
```

### 日志

无

### 服务器环境

服务器版本:
...
This server is running Paper version git-Paper-408 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 0e4f2cc)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-378 (MC: 1.19.3)
...
插件列表:
[21:33:31 INFO]: Server Plugins (18):
[21:33:31 INFO]: Paper Plugins:
[21:33:31 INFO]: Bukkit Plugins:
[21:33:31 INFO]:  - Bank, Core, DeluxeMenus, eco, Essentials, GPS, LuckPerms, MoreFish, Multiverse-Core, MythicMobs
[21:33:31 INFO]:  PlaceholderAPI, PremiumVanish, ProtocolLib, QuickShop-Hikari, Talismans, TheSearch, TrChat, Vault
>

**Comment by YuanYuanOwO** [comment]
在BungeeCord环境下搭配QuickShop-Hikari的BC兼容性插件同样会复现此问题

下载链接：https://github.com/Ghost-chu/QuickShop-Hikari/releases

如果无法加载QuickShop-Hikari请在启动服务器的bat中加入
`-Dcom.ghostchu.quickshop.util.envcheck.EnvironmentChecker.skip.LEGAL_COMPLIANCE_CHECK=true`
或者安装 https://github.com/carm-outsource/QuickShop-Hikari-Cracker

**Comment by xiaofengv233** [comment]
CMI的悬浮字设置也出现了两排字体    和图片上的一样

**Comment by YuanYuanOwO** [comment]
在大概不知道多久之后  
更新了WaterFall跟Paper到最新后似乎解决了该问题 
也可能是重新下载PAPI扩展的原因
