### ISSUE TITLE
[问题]: 请升级TabooLib 版本，推进适配

### ISSUE THREAD

**Issue by ZoruaFox** [FlickerProjects/TrChat#261]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述
不再赘述，请移步DreamVoid/MiraiMC#424

**Comment by ItsFlicker** [comment]
更新 TrChat 至最新的版本

**Comment by ZoruaFox** [comment]
> 更新 TrChat 至最新的版本

https://mclo.gs/HYDWgt4

两个插件版本**均为最新版**，其中 TrChat 使用的是 18 小时之前发布的 2.0.0 ，MiraiMC 使用的是 Actions 中的最新构建，问题未消失。

**Comment by ItsFlicker** [comment]
2.0.0已为TabooLib最新版本6.0.11-20

**Comment by ItsFlicker** [comment]
> [16:52:24] [Server thread/WARN]: [MiraiMC] Unable to download mirai core from remote server, try to use local core. (java.io.FileNotFoundException: https://repo.huaweicloud.com/repository/maven/net/mamoe/mirai-core-all/dev/mirai-core-all-dev-all.jar.md5)

这看起来与TrChat无关，或许是你的网络问题
尝试删除TrChat后能否使用
