### ISSUE TITLE
[问题]: 1.20.1Paper端没有聊天预览功能

### ISSUE THREAD

**Issue by DiritoTech** [FlickerProjects/TrChat#265]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.20.1任意版本paper服务端的server.properties下没有preview-chat选项。
咨询过paper端的开发人员说这个功能被mojang隐藏了，
通过插件或许可以重新开启。
是否意味着trchat这部分的代码逻辑要进行修改呢？

### 配置文件

```YAML
无
```

### 日志

无

### 服务器环境

服务器版本:
PaperSpigot-#71
插件列表:
Trchat，vault，placeholderapi，protocollib

**Comment by ItsFlicker** [comment]
聊天预览的数据包已经删除了
不知道有什么方法启用
