### ISSUE TITLE
[建议]:添加新变量%trchat_message%以及issues的建议以及@bug

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#269]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description
1.12.2@玩家没有反应，后台没有内容
%trchat_message%用于显示玩家当前发言内容
issues是否添加一个新选项用于加建议？

### configuration file

```YAML
no
```

### Server environment

Server version:
...
Plugin list:
...

**Comment by ItsFlicker** [comment]
%trchat_lastmessage%

**Comment by Clexus** [comment]
> %trchat_lastmessage%

这是上一条消息，我想要当前的

**Comment by ItsFlicker** [comment]
2.0.2已改为最新消息
