### ISSUE TITLE
[issue] 添加%trchat_lastmessage_nocolor%，将%trchat_lastmessage%中的颜色符号转译为&

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#274]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

当将%trchat_lastmessage%输出到聊天框并输入时，会因为输入无效字符被踢出服务器
玩家名有屏蔽字符的时候，玩家名会被屏蔽
### configuration file

```YAML
no
```

### Server environment

Server version:
...
Plugin list:
...

**Comment by ItsFlicker** [comment]
%trchat_lastmessage%就是玩家发送的原始信息，不应该有§

**Comment by ItsFlicker** [comment]
> 玩家名有屏蔽字符的时候，玩家名会被屏蔽

https://trchat.trixey.cc/guide/known-issues#%E7%8E%A9%E5%AE%B6%E5%90%8D%E5%AD%97%E8%A2%AB%E8%BF%87%E6%BB%A4

**Comment by Clexus** [comment]
> %trchat_lastmessage%就是玩家发送的原始信息，不应该有§
实际上是包含玩家聊天的格式的

**Comment by ItsFlicker** [comment]
![image](https://github.com/TrPlugins/TrChat/assets/34670283/5a57292c-fcc6-4a07-9393-35e73e558692)

**Comment by Clexus** [comment]
> ![image](https://user-images.githubusercontent.com/34670283/255133213-5a57292c-fcc6-4a07-9393-35e73e558692.png)

尝试用copy方法直接点击文本复制，输出到输入栏的内容是有颜色代码的，而且不是&

**Comment by ItsFlicker** [comment]
![image](https://github.com/TrPlugins/TrChat/assets/34670283/b6593bd7-5057-45a5-93fb-421d1907747b)
![image](https://github.com/TrPlugins/TrChat/assets/34670283/7741d229-0fe8-4177-acc1-ced1c69d04a0)

**Comment by Clexus** [comment]
> ![image](https://user-images.githubusercontent.com/34670283/255135900-b6593bd7-5057-45a5-93fb-421d1907747b.png)
> ![image](https://user-images.githubusercontent.com/34670283/255135951-7741d229-0fe8-4177-acc1-ced1c69d04a0.png)

copy

**Comment by ItsFlicker** [comment]
1.12.2还没有copy功能吧

**Comment by Clexus** [comment]
> 1.12.2还没有copy功能吧

1.12.2的copy就是复制到聊天栏，但是有颜色代码

**Comment by Clexus** [comment]
![image](https://github.com/TrPlugins/TrChat/assets/62130504/26d886ce-0c27-4993-8cca-fdad2c0ccfca)
![image](https://github.com/TrPlugins/TrChat/assets/62130504/cd076cac-3c92-48d7-9de3-b0ca7d599d6d)
用suggest也有这个

**Comment by ItsFlicker** [comment]
1.12.2的copy实质是转化为suggest
大概率是其他插件提前将&变为了§

**Comment by Clexus** [comment]
还有个问题，wiki没有说展示物品里面的
Type: TRANSLATABLE是干什么的，也没有说ChatEvent-Hooks: ['']是干什么的，还有一些都缺失了是不是得添加一下
默认动作例如展示和@的Actions也没有示例，研究了很久也没有执行成功过一个动作

**Comment by ItsFlicker** [comment]
Type: TRANSLATABLE和ChatEvent-Hooks在新版本已删除，没有任何作用

**Comment by ItsFlicker** [comment]
%trchat_lastmessage_uncolored%
