### ISSUE TITLE
[问题] 可能是以下原因导致的服务器无法使用@，/msg，/mute功能

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#276]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

[16:00:15] [Server thread/INFO]: [TrChat] Enabling TrChat v2.0.2
[16:00:15] [Server thread/WARN]: [TrChat] io.papermc.paper.event.player.AsyncChatEvent not found, use @Ghost to turn off this warning

### 配置文件

```YAML
无
```

### 服务器环境

服务器版本:
paper-1.12.2-1618
插件列表:
![image](https://github.com/TrPlugins/TrChat/assets/62130504/ffe1ec4e-459b-469f-a8a3-4dd62689c830)

**Comment by ItsFlicker** [comment]
忘记关闭这个警告了
无法使用@，/msg，/mute说明玩家列表未同步
是否在bc安装了trchat?
尝试换用redis同步模式

**Comment by Clexus** [comment]
> 忘记关闭这个警告了 无法使用@，/msg，/mute说明玩家列表未同步 是否在bc安装了trchat? 尝试换用redis同步模式

bc端未安装

**Comment by ItsFlicker** [comment]
bc模式依赖bc端的trchat来传递玩家列表

**Comment by ericzhu1228** [comment]
bc模式能关吗

**Comment by ItsFlicker** [comment]
> bc模式能关吗

settings.yml中Proxy改为NONE或打开redis

**Comment by Dreeam-qwq** [comment]
> > bc模式能关吗
> 
> settings.yml中Proxy改为NONE或打开redis

仍旧无法使用msg或者@或者mute

**Comment by ItsFlicker** [comment]
@Dreeam-qwq bc与子服trchat版本是否一致?
只有单端是否能使用?

**Comment by Dreeam-qwq** [comment]
> @Dreeam-qwq bc与子服trchat版本是否一致? 只有单端是否能使用?

单端可以正常使用，套上Velocity就不行了(装了相同版本的TrChat，都是最新commit 2.0.3)，

**Comment by Clexus** [comment]
和我的问题一样

**Comment by ItsFlicker** [comment]
> > @Dreeam-qwq bc与子服trchat版本是否一致? 只有单端是否能使用?
> 
> 单端可以正常使用，套上Velocity就不行了(装了相同版本的TrChat，都是最新commit 2.0.3)，

能否上传一下Velocity端?

**Comment by Dreeam-qwq** [comment]
原链接 https://api.papermc.io/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/260/downloads/velocity-3.2.0-SNAPSHOT-260.jar

velocity [velocity.zip](https://github.com/TrPlugins/TrChat/files/12165098/velocity.zip)

**Comment by ItsFlicker** [comment]
@Dreeam-qwq 需要的是配置文件..
尝试将settings.yml的Proxy改为VELOCITY

**Comment by Dreeam-qwq** [comment]
> @Dreeam-qwq 需要的是配置文件.. 尝试将settings.yml的Proxy改为VELOCITY

解决了，另外我之前在private.yml把proxy设为false了，怪不得用不了私聊(
谢谢大佬(
