### ISSUE TITLE
[功能] 配置文件中，关于 condition 的更多可用选项有哪些

### ISSUE THREAD

**Issue by SakuraTao2007** [FlickerProjects/TrChat#280]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

配置文件中，关于 condition 的更多可用选项有哪些，是属于坏黑库中的内容吗

**Comment by Clexus** [comment]
请查看Kether
