### ISSUE TITLE
[问题] Bungeecord登录Paper1.19.2子服无法使用私聊功能

### ISSUE THREAD

**Issue by 1105204358** [FlickerProjects/TrChat#283]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.登录后进入Paper子服服务器输入/tell 后不出现在线玩家的名字作提示。
2.输入后显示参数错误，私聊功能无法使用。
经过测试更换为waterfall依旧有问题无法使用，
但是关闭群组后直接子服连接正常使用。

### 配置文件

```YAML
settings:
https://mclo.gs/5DJbDdj
```

### 日志

![bugT](https://github.com/TrPlugins/TrChat/assets/44061770/5e92cf4a-4b56-4d15-9260-ed4d451920c1)

### 服务器环境

服务器版本:
paper-1.19.2-307
插件列表:
![image](https://github.com/TrPlugins/TrChat/assets/44061770/f0505277-5f97-4873-864a-2a6adba253c2)

**Comment by ItsFlicker** [comment]
bc需安装trchat

**Comment by 1105204358** [comment]
好的，已经解决了，谢谢您
