### ISSUE TITLE
[问题] 玩家没有权限也可以使用颜色

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#285]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

玩家可以使用类似于&a的代码直接发送带颜色的内容，就算已经设置trchat.color.*都为false也不行

### 配置文件

```YAML
无
```

### 服务器环境

服务器版本:
...
插件列表:
...

**Comment by ItsFlicker** [comment]
![image](https://github.com/TrPlugins/TrChat/assets/34670283/8128db87-1b58-4b30-8236-555d489d4de3)
