### ISSUE TITLE
[功能] 请求增加为 TrChat 关闭其历史消息记录的功能

### ISSUE THREAD

**Issue by Azrael070** [FlickerProjects/TrChat#287]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

当一个服务器一段时间内未开启时，再启动后，第一个玩家进入该服务器时，会一次性接收到这个服务器停服期间所有来自 BungeeCord 频道的聊天消息，随后该玩家就会被服务器以发包过多为由踢出（Sent too many packets）
在目前的配置文件没找到关于这块的内容，经询问后得知这是由来已久的问题。

**Comment by ItsFlicker** [comment]
bc有安装其他插件吗

**Comment by ItsFlicker** [comment]
不知道什么原因，实际上没有这样的功能

**Comment by Azrael070** [comment]
> 不知道什么原因，实际上没有这样的功能

在发此 issue 之前，我在 mcbbs 发过提问帖求助，回答者有提到这个问题在最新版本的 TrChat 依旧存在。
https://search.mcbbs.net/thread-1459609-1-1.html

**Comment by Azrael070** [comment]
> 不知道什么原因，实际上没有这样的功能

举个例子：BC下有 A、B、C 三个服，A 服和 B 服长期运行，C 服一直停着
现在把 C 服开起来，然后进 C 服，则 C 服停服期间，所有在 BC 频道下的聊天记录会一次性发送到我的公屏。

**Comment by ItsFlicker** [comment]
可能修复
[TrChat-2.0.4.zip](https://github.com/TrPlugins/TrChat/files/12206358/TrChat-2.0.4.zip)
