### ISSUE TITLE
[功能] 请求增加屏蔽切换功能

### ISSUE THREAD

**Issue by fyxrim** [FlickerProjects/TrChat#288]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
增加屏蔽切换功能

比如
/ignore XXX on 开启屏蔽XXX玩家
/ignore XXX off 关闭屏蔽XXX玩家

我写的trmenu 玩家列表菜单 要求这个
```

**Comment by fyxrim** [comment]
Hello 忘记要求一个变量

%trchat_ignore% 显示 已屏蔽/未屏蔽

**Comment by ItsFlicker** [comment]
2.0.5 %trchat_ignore_`player`%
