### ISSUE TITLE
[问题] 展示物品显示Invalid Item

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#289]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

不清楚触发逻辑，展示某些物品时除了名字，会显示Invalid Item，如果把兼容模式打开，全部会变成石头
兼容模式打开后：
原物品：
![image](https://github.com/TrPlugins/TrChat/assets/62130504/30800704-294e-4b5b-9343-2a10c0ff906e)
实际展示:
![image](https://github.com/TrPlugins/TrChat/assets/62130504/8b2632bb-2cbf-4d46-8508-99501c7e49c6)

### 配置文件

```YAML
默认
```

### 日志

无

### 服务器环境

服务器版本:
Paper-1618 1.12.2
插件列表:
.

**Comment by ItsFlicker** [comment]
已解决
