### ISSUE TITLE
[功能] 添加/r回复的功能

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#290]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

字面意思

**Comment by ItsFlicker** [comment]
已有，权限为trchat.private

**Comment by Clexus** [comment]
> 已有，权限为trchat.private

指的是/r 信息 直接回复上一个人，我貌似没见到这个功能

**Comment by ItsFlicker** [comment]
![image](https://github.com/TrPlugins/TrChat/assets/34670283/f484e463-75f8-48d6-8a32-674882e29581)

**Comment by Clexus** [comment]
> ![image](https://user-images.githubusercontent.com/34670283/257126766-f484e463-75f8-48d6-8a32-674882e29581.png)

装有Essentials的时候这个指令优先为essentials的回复功能

**Comment by ItsFlicker** [comment]
Essentials应该能关闭特定指令

**Comment by Clexus** [comment]
> Essentials应该能关闭特定指令

貌似是不能关闭回复这个指令的
