### ISSUE TITLE
[功能] 增加对插件的颜色支持

### ISSUE THREAD

**Issue by littlekan233** [FlickerProjects/TrChat#291]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

1. 此功能针对彩虹颜色无法在众多插件上正常显示：
![image](https://github.com/TrPlugins/TrChat/assets/75866787/620edc36-f5b2-47c2-90e1-eedc77189a0f)
 
![image](https://github.com/TrPlugins/TrChat/assets/75866787/cc2b34c2-bed4-4619-a6fd-d64414a46c26)

2.给TAB插件增加渐变简化（TAB插件已存在，但是TrChat的有简写，TAB插件没有且不方便）
![image](https://github.com/TrPlugins/TrChat/assets/75866787/a4864bb8-0190-4f03-82ac-de7d079af5aa)

3. 具体实现可以参考https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-glow-plugins

**Comment by ItsFlicker** [comment]
不太可能实现
> https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-glow-plugins

这是对发光插件的兼容

**Comment by littlekan233** [comment]
那好吧
