### ISSUE TITLE
[功能] 自动创建的每个世界独立的聊天频道

### ISSUE THREAD

**Issue by PixelEast** [FlickerProjects/TrChat#292]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

我的服务器使用了一些插件来为玩家自动创建他们自己的世界，我想实现PerWorldChat的功能，每个玩家世界的聊天频道分开，玩家默认会加入世界的聊天频道，而不是normal频道

**Comment by ItsFlicker** [comment]
用Target: single_world不行吗

**Comment by PixelEast** [comment]
> 用Target: single_world不行吗

谢谢，我回头去试试看
