### ISSUE TITLE
[功能] 扩展对DiscordSRV的支持-指定聊天频道不同步到Discord频道

### ISSUE THREAD

**Issue by YuanYuanOwO** [FlickerProjects/TrChat#293]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

配置文件增加只同步到Discord的聊天频道，或者添加指定聊天频道不同步到Discord的配置方式

**Comment by ItsFlicker** [comment]
2.0.5已支持 (未测试，可能有bug)
https://trchat.trixey.cc/guide/channel/settings#%E9%80%89%E9%A1%B9

**Comment by YuanYuanOwO** [comment]
> 2.0.5已支持 (未测试，可能有bug) https://trchat.trixey.cc/guide/channel/settings#%E9%80%89%E9%A1%B9

十分感谢！
简单测试了一下没有问题
