### ISSUE TITLE
[功能] WIKI要更新了

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#294]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
插件自带的变量没写上去
格式部分有更新也没写上去
```

**Comment by ItsFlicker** [comment]
已更新
