### ISSUE TITLE
[问题] 

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#295]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

2.0.4后禁言除了永久禁言外没有其他选择
![image](https://github.com/TrPlugins/TrChat/assets/62130504/9ef1fd52-a5ea-42ce-8501-bad771b7a5df)
![image](https://github.com/TrPlugins/TrChat/assets/62130504/458bc6ce-8d5c-4b45-b139-8b3d6247c4ef)

### 配置文件

```YAML
无
```

### 服务器环境

服务器版本:
...
插件列表:
...

**Comment by ItsFlicker** [comment]
-t=10d

**Comment by Clexus** [comment]
> -t=10d

不加原因没有用，但是原因不论是-r xxx 还是-r=xxx都没用
取消禁言用/mute xxx --cancel也没用了

**Comment by ItsFlicker** [comment]
换用了tb的解析器，现在是 -cancel

**Comment by Clexus** [comment]
> 换用了tb的解析器，现在是 -cancel

貌似原因和时间不能同时解析
![image](https://github.com/TrPlugins/TrChat/assets/62130504/c76bde76-ee7c-4e8f-8432-6df376ede539)
![image](https://github.com/TrPlugins/TrChat/assets/62130504/2fa3e092-430c-42d3-93fe-88fe501432b6)
![image](https://github.com/TrPlugins/TrChat/assets/62130504/2dfa6aa0-df7a-48ea-8a7f-3932f58115ab)

-cancel也没用
![image](https://github.com/TrPlugins/TrChat/assets/62130504/3f2989a9-221a-40af-8702-35062dc301bb)
