### ISSUE TITLE
[功能] 扩展DiscordSRV的支持-增加屏蔽Discord聊天频道讯息的切换功能

### ISSUE THREAD

**Issue by vc606** [FlickerProjects/TrChat#297]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

新增 /trchat chatDiscordSRV 指令 

进去可以切换聊天频道是否显示DiscordSRV聊天的讯息

可以选择频道要不要显示有discordsr讯息聊天的切换
(有些玩家不爱看discordsrv频道的对话于游戏内)

或是可以进入A频道discords聊天与游戏聊天都会显示
进入B频道 只会显示游戏内的聊天讯息 对话分频之类的

我使用chatFilter尝试阻挡[DiscordSRV] 之类的没有作用

搜寻一些聊天插件似乎没有支援这一项功能
希望能否支持这个功能 谢谢您

**Comment by ItsFlicker** [comment]
2.0.5已支持 (未测试，可能有bug)
https://trchat.trixey.cc/guide/channel/settings#%E9%80%89%E9%A1%B9
需要创建两个频道，一个显示，一个不显示

**Comment by vc606** [comment]
> 2.0.5已支持（未測試，可能有bug） https://trchat.trixey.cc/guide/channel/settings#%E9%80%89%E9%A1%B9 需要創建兩個，一個頻道，一個不顯示


目前 測試是否接受DiscordSRV的消息 功能正常 很感谢作者添加此功能 

我寻找许多插件都没有找到有支援此功能的 真的很感谢您添加

但我发现cmi聊天插件有设定关闭

```
聊天重复
关闭 CMI/Settings/Chat.yml 中的 ModifyChatFormat 和 ClickHoverMessages
```
会让bungee 其他服务器會看到是重复聊天 发生情形不明  
(自己打字没看到 是隔壁服务器会看到)

我肯定cmi的兩個選項都有更改為false

我有空再多测试一下不确定是不是我的问题 辛苦您了

**Comment by vc606** [comment]
> 

目前测试 关闭cmi.bungee.publicmessages.[服务器名称] 权限点后 聊天都蛮正常的 感谢作者
