### ISSUE TITLE
TrChat-1.81 Arclight服务端无法使用过滤物品功能

### ISSUE THREAD

**Issue by Yurinann** [FlickerProjects/TrChat#3]
报错信息: https://paste.ubuntu.com/p/h4W6Kr9Ngz/

环境: 
1.16.5 Arclight (Aug 19 version) 
Java 16
TrChat 1.81

待更新环境测试

**Comment by SouthTownt** [comment]
补充：使用非 mod 服务端 (Purpur) 测试无此报错

**Comment by SouthTownt** [comment]
再次补充：重复测试，感觉不是发送消息会报错，而是玩家加入时重复刷两次。

**Comment by ItsFlicker** [comment]
这东西有点怪...
应该是打开容器/选择快捷栏就会报错
我就调用了CraftItemStack.asCraftMirror
目前我只能忽略报错来解决(无法过滤物品name和lore)
应该是arclight的锅

**Comment by SouthTownt** [comment]
唔 感觉有可能
出现的基本没有规律 能确定的是玩家不在游戏的时候不会有这个报错 应该和玩家有关
我想给arclight 1.16 发一个issue
用purpur又试了一遍 看起来完全没出现

**Comment by ItsFlicker** [comment]
相关代码: [https://github.com/FlickerProjects/TrChat/blob/master/src/main/kotlin/me/arasple/mc/trchat/api/nms/PacketUtilsImpl.kt](url)

**Comment by Yurinann** [comment]
所有最新版无报错 @ItsFlicker
