### ISSUE TITLE
[功能请求] 翻译监听玩家私聊中 %i 到底展示了什么

### ISSUE THREAD

**Issue by postyizhan** [FlickerProjects/TrChat#302]
### Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### Detailed description

插件版本:2.0.4
MC版本:1.20.1
并没有产生报错，所以我觉得这不是BUG/ERROR
我希望可以看到玩家在私聊中使用%i到底展示了什么
![图片](https://github.com/TrPlugins/TrChat/assets/97342038/7cad0078-1f13-4e16-bac5-6811ea0ca9f6)

**Comment by ItsFlicker** [comment]
已支持
但由于语言系统的限制，悬浮事件未添加
