### ISSUE TITLE
[功能] 直接使用mute命令禁言 并不是好主意

### ISSUE THREAD

**Issue by JSWuMing** [FlickerProjects/TrChat#303]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

部分插件同样拥有mute这个命令
从而导致命令冲突
建议将mute
给为trmute

**Comment by postyizhan** [comment]
我也使用 /mute禁言 他显示了
![图片](https://github.com/TrPlugins/TrChat/assets/97342038/82efaf82-714a-4b92-b7e2-387627c3a1ed)
它显示禁言了999d 正常禁言，除了时间不太对

我记得以前的用法是 /mute ID -t 15m
![图片](https://github.com/TrPlugins/TrChat/assets/97342038/48bf1927-ea20-4294-a640-1674e51c2b77)
但是这位玩家仍然可以正常发言

所以我觉得禁言可能坏了，这是个bug

**Comment by Clexus** [comment]
> 我也使用 /mute禁言 他显示了 ![图片](https://user-images.githubusercontent.com/97342038/260265066-82efaf82-714a-4b92-b7e2-387627c3a1ed.png) 它显示禁言了999d 正常禁言，除了时间不太对
> 
> 我记得以前的用法是 /mute ID -t 15m ![图片](https://user-images.githubusercontent.com/97342038/260265057-48bf1927-ea20-4294-a640-1674e51c2b77.png) 但是这位玩家仍然可以正常发言
> 
> 所以我觉得禁言可能坏了，这是个bug
https://github.com/TrPlugins/TrChat/issues/295

**Comment by WarmRhombus** [comment]
确实，而且他好像禁言不了一些玩家的名字，显示未找到该玩家，是因为名字太长了？
