### ISSUE TITLE
[功能]  建议展示潜影盒的是打开潜影盒的物品的gui而不是只展示潜影盒

### ISSUE THREAD

**Issue by xiaojinxs69** [FlickerProjects/TrChat#305]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

当前已经更新了展示物品打开gui，可以增加个展示潜影盒，展示的内容是潜影盒里面的物品

**Comment by ItsFlicker** [comment]
已完成
https://github.com/TrPlugins/TrChat/actions/runs/7357248308
