### ISSUE TITLE
[功能] 能让trchat在bungee端上不用bungee只在单端中获取玩家列表吗

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#311]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述
我有bungee,但是我只有一个登录服和一个主服，登录服不需要trchat

**Comment by ItsFlicker** [comment]
用redis模式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月23日(周三) 下午5:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TrPlugins/TrChat] [功能] 能让trchat在bungee端上不用bungee只在单端中获取玩家列表吗 (Issue #311)




 
是否已查阅 Wiki
  
 我已查阅 Wiki 并确定没有存在该功能.
  
是否存在重复 issue
  
 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.
  
详细的描述
 
标题

**Comment by Clexus** [comment]
没有redis

**Comment by ItsFlicker** [comment]
Proxy: AUTO改为Proxy: NONE
