### ISSUE TITLE
[功能] 请求添加加入频道状态变量

### ISSUE THREAD

**Issue by fyxrim** [FlickerProjects/TrChat#312]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
1. ...
2. ...
3. ...
```
如题

**Comment by ItsFlicker** [comment]
%trchat_channel%?




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月24日(周四) 凌晨4:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TrPlugins/TrChat] [功能] 请求添加加入频道状态变量 (Issue #312)




 
是否已查阅 Wiki
  
 我已查阅 Wiki 并确定没有存在该功能.
  
是否存在重复 issue
  
 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.
  
详细的描述
 1. ... 2. ... 3. ...  
如题

**Comment by fyxrim** [comment]
> %trchat_channel%?
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月24日(周四) 凌晨4:11 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [TrPlugins/TrChat] [功能] 请求添加加入频道状态变量 (Issue #312) 是否已查阅 Wiki 我已查阅 Wiki 并确定没有存在该功能. 是否存在重复 issue 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述. 详细的描述 1. ... 2. ... 3. ... 如题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

YES，加入了吗？

**Comment by ItsFlicker** [comment]
早就有了
