### ISSUE TITLE
[Feature] ia变量兼容

### ISSUE THREAD

**Issue by BlindspotCheat** [FlickerProjects/TrChat#316]
### Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### Detailed description

希望能兼容ia的图片变量 
我是以%img_rank%的形式展示权限组前后缀的
而且目前好像很多插件都是主要对%img_image%这种形式的图片展示进行兼容的

**Comment by ItsFlicker** [comment]
2.0.11可能修复
