### ISSUE TITLE
[功能] 请求屏蔽玩家状态变量

### ISSUE THREAD

**Issue by fyxrim** [FlickerProjects/TrChat#318]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
1. ...
2. ...
3. ...
```
如题

**Comment by ItsFlicker** [comment]
https://trchat.trixey.cc/guide/placeholderapi
