### ISSUE TITLE
[问题]屏蔽词数据库已失效

### ISSUE THREAD

**Issue by JiJiang233** [FlickerProjects/TrChat#320]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.屏蔽词库指向一个不可访问的网址(ERR_ADDRESS_INVALID)

### 配置文件

```YAML
filter.yml
```

### 服务器环境

服务器版本:
1.20.1
插件列表:
...

**Comment by ItsFlicker** [comment]
未失效
![image](https://github.com/TrPlugins/TrChat/assets/34670283/ba1b867f-5180-47e5-8369-88f6786d6ac4)
