### ISSUE TITLE
[功能] 屏蔽词库格式增加支持一行一词

### ISSUE THREAD

**Issue by YuanYuanOwO** [FlickerProjects/TrChat#321]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

屏蔽词库文件的格式支持增加一行一词语，如下方例子所示，不需要对每个词语进行引用
```
屏蔽词A  
屏蔽词B
屏蔽词C
屏蔽词D
........
```

**Comment by ItsFlicker** [comment]
```yaml
Local: |-
  屏蔽词A  
  屏蔽词B
  屏蔽词C
```
