### ISSUE TITLE
[功能] 聊天格式支持换行符

### ISSUE THREAD

**Issue by humonia-sys** [FlickerProjects/TrChat#328]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
1. 可以在格式组件中自定义换行,如
```
![图片](https://github.com/TrPlugins/TrChat/assets/85441099/ed1b1713-dfdb-4df2-bdc6-a0c81c060f4c)

**Comment by ItsFlicker** [comment]
将单引号改为双引号
```yaml
part-before-player:
  text: "\n"
```
