### ISSUE TITLE
[功能] 支持中文频道名，或者自定义频道显示名

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#331]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

玩家切换频道看到的是英文ID，显得很别扭

**Comment by ItsFlicker** [comment]
现在不支持吗

**Comment by Clexus** [comment]
> 现在不支持吗

中文频道名在返回时会出错（例如从私聊频道退出进入普通频道）

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/6993372151应该修复
