### ISSUE TITLE
[功能] 悬浮物品&实体

### ISSUE THREAD

**Issue by LinRanAstra** [FlickerProjects/TrChat#335]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

想询问一下关于官方wiki中有两个悬浮事件其
hoveritem和hoverentity
想询问一下这两个悬浮事件是否已经开始开发或者已经放弃？
如果正在开发请问有多久能够正式上线？

**Comment by ItsFlicker** [comment]
没想到用途
暂时不开发
