### ISSUE TITLE
[问题] 麻烦支持一下1.20.4 QAQ

### ISSUE THREAD

**Issue by CuteLittleSky** [FlickerProjects/TrChat#339]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

RT. TABOOLIB已支持1.20.4

### 配置文件

```YAML
.
```

### 服务器环境

.

**Comment by CCjun6** [comment]
我也在等待1.20.4 麻烦作者有空更新下

**Comment by ItsFlicker** [comment]
已支持
https://github.com/TrPlugins/TrChat/actions/runs/7357248308
