### ISSUE TITLE
[功能] 特定频道内容传至Discord指定频道

### ISSUE THREAD

**Issue by MOMOas** [FlickerProjects/TrChat#342]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
vip 频道内容传至到  Discord 指定频道 例如
  # 是否传输消息到DiscordSRV
  Send-To-Discord: true
  Channel-ID: 1134891537776513204
  
```
![Discord_3NX5TN18dl](https://github.com/TrPlugins/TrChat/assets/25352223/9c41bbd8-fb37-4e27-b34c-3b4fa2dfe0cf)

**Comment by CuteLittleSky** [comment]
如果要做的话QQ频道也可以来一下:D

**Comment by MOMOas** [comment]
> 如果要做的話QQ頻道也可以來一下:D

請問QQ頻道多少?

**Comment by ItsFlicker** [comment]
```yaml
Options:
  Discord-Channel: xxx
```

**Comment by MOMOas** [comment]
> ```yaml
> Options:
>   Discord-Channel: xxx
> ```
使用后无法显示到该频道

**Comment by ItsFlicker** [comment]
需要用2.0.11

**Comment by MOMOas** [comment]
> ```yaml
> Discord-Channel: 
> ```
更新最新版还是一样无法传送到指定频道

**Comment by MOMOas** [comment]
DiscordSRV-Build-1.26.2

**Comment by ItsFlicker** [comment]
可能是无法使用数字ID
要用`Discord-Channel: "global"`之类的

**Comment by MOMOas** [comment]
> 可能是无法使用数字ID 要用`Discord-Channel: "global"`之类的
我复制频道名称他还是没显示到该频道
  Discord-Channel: "🏄｜vip聊天頻道"
![image](https://github.com/TrPlugins/TrChat/assets/25352223/1377937d-e730-4ba6-bbe2-23d436422088)

**Comment by ItsFlicker** [comment]
应该是要在DiscordSRV配置文件写对应关系
```yaml
# DiscordSRV的所有消息将转到第一个通道，除非为该消息定义了一个通道:
# 使用兼容的聊天插件之一时，频道名称将来自该插件（用于聊天消息）
#  - 如果您使用的是TownyChat，则默认频道通常称为"general"而不是"global"
# 用于播放器聊天消息（不使用聊天插件时）: global
# 用于服务器启动/停止消息: status
# 成就/进阶讯息编号: awards
# 死亡消息: deaths
# 加入消息: join
# 留言留言: leave
# 用于dynmap消息: dynmap
# 用于看门狗消息: watchdog
# 用于/discord broadcast: broadcasts（除非在命令中指定）
# 帐户链接: link
#
# "频道对的第一部分不是Discord频道名称！
# 更改此选项并运行“/discord reload”以应用
Channels: {"global": "000000000000000000"}
```

**Comment by MOMOas** [comment]
> 应该是要在DiscordSRV配置文件写对应关系
> 
> ```yaml
> # DiscordSRV的所有消息将转到第一个通道，除非为该消息定义了一个通道:
> # 使用兼容的聊天插件之一时，频道名称将来自该插件（用于聊天消息）
> #  - 如果您使用的是TownyChat，则默认频道通常称为"general"而不是"global"
> # 用于播放器聊天消息（不使用聊天插件时）: global
> # 用于服务器启动/停止消息: status
> # 成就/进阶讯息编号: awards
> # 死亡消息: deaths
> # 加入消息: join
> # 留言留言: leave
> # 用于dynmap消息: dynmap
> # 用于看门狗消息: watchdog
> # 用于/discord broadcast: broadcasts（除非在命令中指定）
> # 帐户链接: link
> #
> # "频道对的第一部分不是Discord频道名称！
> # 更改此选项并运行“/discord reload”以应用
> Channels: {"global": "000000000000000000"}
> ```
这样有了! 谢谢你
