### ISSUE TITLE
[问题]Discord转发问题

### ISSUE THREAD

**Issue by YuanYuanOwO** [FlickerProjects/TrChat#347]
![{8AA5B518-6450-4751-9843-3BE8799742A4}](https://github.com/TrPlugins/TrChat/assets/81153017/b0e34fbb-8304-41d7-b698-463c3ecf1429)
上放为 2.0.9 版本的TrChat转发格式，下方为 2.0.11 的TrChat转发格式
请问我要怎么做才能保持 2.0.9 版本的转发格式呢

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/8030903080 已恢复
