### ISSUE TITLE
[功能] 取消mute、muteall命令注册

### ISSUE THREAD

**Issue by gyc123456-1** [FlickerProjects/TrChat#352]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

可在配置文件开关禁言命令的注册

主要是因为这个命令也要被我其他插件注册，想把trchat的关掉

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/8030903080
添加
```yaml
Options:
  Disabled-Commands: ['mute', 'muteall']
```
