### ISSUE TITLE
[功能] 转发到QQ频道

### ISSUE THREAD

**Issue by jdnjk** [FlickerProjects/TrChat#362]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
1. ...支持转发到QQ频道
```

**Comment by ItsFlicker** [comment]
怎么支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月20日(周二) 上午10:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TrPlugins/TrChat] [功能] 转发到QQ频道 (Issue #362)




 
是否已查阅 Wiki
  
 我已查阅 Wiki 并确定没有存在该功能.
  
是否存在重复 issue
  
 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.
  
详细的描述
 1. ...支持转发到QQ频道

**Comment by Muska-Ami** [comment]
这加到TrChat会不会太臃肿了...

建议参考我的API+TrChat API实现（QQ频道主动消息量很少，所以没有支持主动消息）
[https://github.com/Muska-Ami/LinerRX](https://github.com/Muska-Ami/LinerRX)

**Comment by jdnjk** [comment]
> 这加到TrChat会不会太臃肿了...
> 
> 建议参考我的API+TrChat API实现（QQ频道主动消息量很少，所以没有支持主动消息）
> [https://github.com/Muska-Ami/LinerRX](https://github.com/Muska-Ami/LinerRX)

如果这样和附属插件有何区别

**Comment by Muska-Ami** [comment]
> > 这加到TrChat会不会太臃肿了...
> > 
> > 建议参考我的API+TrChat API实现（QQ频道主动消息量很少，所以没有支持主动消息）
> > [https://github.com/Muska-Ami/LinerRX](https://github.com/Muska-Ami/LinerRX)
> 
> 如果这样和附属插件有何区别

这本来就应该是附属插件来实现的功能，首先TrChat是针对于Minecraft聊天开发的，那么转发到其他地方则应该由附属插件操作而不是直接改动本体。
例子参考我的CatSero（转发到QQ群，因tx的逆天操作已永久弃坑）
