### ISSUE TITLE
[问题] 原版物品显示NO_LOCALE

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#369]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

如题

### 配置文件

```YAML
无
```

### 服务器环境

服务器版本:
Paper-1.12.2-1618
插件列表:
和其他插件应该没关系

**Comment by ItsFlicker** [comment]
TabooLib/taboolib/pull/416

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/8409166538
