### ISSUE TITLE
[功能] 每次更新可以加个更新日志吗

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#374]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

每次更新小版本修了什么bug加了什么功能都不知道

**Comment by ItsFlicker** [comment]
2.0.12-2.1.0的一并发了
之后每个版本会添加
