### ISSUE TITLE
[功能] 龙核生僻字替换图片

### ISSUE THREAD

**Issue by c76916892** [FlickerProjects/TrChat#378]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

如果龙核的FontConfig里的某一个生僻字color: true，聊天时§生僻字 无法显示被龙核替换的图片

![1](https://github.com/TrPlugins/TrChat/assets/59474947/4d4f8002-d9fd-47ee-8ffd-7ba1314f799a)
![2](https://github.com/TrPlugins/TrChat/assets/59474947/1ada0c7d-3bb1-434a-8153-6e6fa512160d)
![3](https://github.com/TrPlugins/TrChat/assets/59474947/a44ff4d7-77e2-4298-afdc-43f525fc2372)

**Comment by FxRayHughes** [comment]
我也遇到了这个问题 应该是替换中过于暴力的替换了所有的 颜色符号后面的文字

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/9451980664
