### ISSUE TITLE
[功能] redis如何使用，wiki教程不够详细

### ISSUE THREAD

**Issue by mc23101** [FlickerProjects/TrChat#381]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
redis如何使用，wiki中对于reids的说明不够详细，
在对于redis连接中，redis用户通常不会设置，只会单纯设置密码，请问如何填写参数
```

**Comment by ItsFlicker** [comment]
不需要改变默认参数
