### ISSUE TITLE
[功能] 如何在跨服聊天之外，平时就用ess的聊天前缀

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [FlickerProjects/TrChat#382]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
1. ...
2. ...
3. ...
```
平常聊天还是用我的ess聊天格式吧，这个无论怎么改都是全局默认跨服聊天，就算我把所有端的都改成Normal。
![IMG_20240408_105919](https://github.com/TrPlugins/TrChat/assets/141799770/ad616012-1c85-4bf6-aa57-f2cc4a9dc9d9)
![Screenshot_2024-04-08-11-08-31-564_com tungsten fcl](https://github.com/TrPlugins/TrChat/assets/141799770/f87ab5c3-c1c5-41f1-a63e-6b60a2bf01f7)
![Screenshot_2024-04-08-11-19-14-649_com tungsten fcl-edit](https://github.com/TrPlugins/TrChat/assets/141799770/83049d8b-256d-4c6b-a975-0a18f496c47b)
![Screenshot_2024-04-08-10-58-43-638_com tungsten fcl-edit](https://github.com/TrPlugins/TrChat/assets/141799770/8298c4d3-7bda-4798-a8a0-1938400fc881)

**Comment by konsheng** [comment]
这边建议使用esschat，别用trchat了

**Comment by MinecraftEarthVillage** [comment]
> 这边建议使用esschat，别用trchat了

可是ess没有跨服通话功能
