### ISSUE TITLE
[Feature] /tell指令里会出现两个相同玩家名，其中一个作为私聊目标后会断开连接

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [FlickerProjects/TrChat#383]
### Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### Detailed description

```
1. ...
2. ...
3. ...
```
输入/tell 
候选词里每个人都有两个名字，其中一个是带有颜色符号的(就是那个像两个S叠一起的那个)
如果选择不带颜色符号的玩家名，则功能正常使用，如果选择带颜色符号的名字，私聊发出后发送者就会断开连接

https://github.com/TrPlugins/TrChat/assets/141799770/b45f1b5f-187a-45eb-87a9-09ab450f05b1

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/8770523938 修复
