### ISSUE TITLE
[问题] 个人信息公钥丢失

### ISSUE THREAD

**Issue by McAZero** [FlickerProjects/TrChat#389]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

1.20.4版本使用trchat会提示“个人信息公钥丢失”
群组中1.16 1.18并不会这样已安装最新版的trchat
请问这是什么问题

### 配置文件

```YAML
未修改settings
```

### 日志

 Failed to update secure chat state for asdyui: 'Chat disabled due to missing profile public key. Please try reconnecting.'

### 服务器环境

服务器版本:
purpur-1.20.4-2172
插件列表:
[11:06:52 INFO]: Bukkit Plugins: (7):
[11:06:52 INFO]:  - CMI, CMILib, PlaceholderAPI, ProtocolLib, spark, TrChat, Vault

**Comment by ItsFlicker** [comment]
https://trchat.trixey.cc/guide/known-issues#%E7%8E%A9%E5%AE%B6%E5%9B%A0-%E8%81%8A%E5%A4%A9%E6%B6%88%E6%81%AF%E9%AA%8C%E8%AF%81%E5%A4%B1%E8%B4%A5-%E8%A2%AB%E8%B8%A2%E5%87%BA

**Comment by McAZero** [comment]
> https://trchat.trixey.cc/guide/known-issues#%E7%8E%A9%E5%AE%B6%E5%9B%A0-%E8%81%8A%E5%A4%A9%E6%B6%88%E6%81%AF%E9%AA%8C%E8%AF%81%E5%A4%B1%E8%B4%A5-%E8%A2%AB%E8%B8%A2%E5%87%BA

谢谢，已解决
