### ISSUE TITLE
[功能] 支持1.20.5

### ISSUE THREAD

**Issue by mjiangmc** [FlickerProjects/TrChat#397]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
1. 希望支持1.20.5版本的服务器使用
```

**Comment by HaHaWTH** [comment]
UP
