### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by DJelly4K** [FlickerProjects/TrChat#40]
Error log: https://pastebin.com/6Lgwvtc5
刚开始加载显示加载正常并且已经有了输出，过了一会儿就直接报错然后关闭
服务端：
Proxy: [FlameCord](https://github.com/2lstudios-mc/FlameCord) 0.6.8 (a waterfall/bungeecord fork)
Backend Server: [Patina 1.17.1](https://github.com/PatinaMC/Patina) (a paper fork)
设置里已开启 BUNGEE 模式
TrChat版本：TrChat v1.90-R5 （最新开发版，去github actions那里下载的）

**Comment by DJelly4K** [comment]
? why close this

**Comment by ItsFlicker** [comment]
https://github.com/FlickerProjects/TrChat/actions/runs/1623397713

**Comment by DJelly4K** [comment]
> https://github.com/FlickerProjects/TrChat/actions/runs/1623397713

![image](https://user-images.githubusercontent.com/68630033/147400657-879799fc-ef8a-4d61-ad01-f59110224e1d.png)

**Comment by ItsFlicker** [comment]
请检查每一个format里有没有配置msg

**Comment by DJelly4K** [comment]
没问题啊
https://pastebin.com/faGvvpPi

**Comment by ItsFlicker** [comment]
GLOBAL没有msg

**Comment by DJelly4K** [comment]
> 

草，明白了
