### ISSUE TITLE
[issue] The permissions required to register the command on velocity are invalid

### ISSUE THREAD

**Issue by CatTeaA** [FlickerProjects/TrChat#406]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

Everyone can use this command:    /muteallservers on & off
A check by Luckperms-Velocity shows that Trchat has not registered any permissions on Velocity

https://github.com/TrPlugins/TrChat/blob/d3d059b85313629cf87e6880c0585f821cb07e13/project/runtime-velocity/src/main/kotlin/me/arasple/mc/trchat/module/internal/TrChatVelocity.kt#L36

### configuration file

```YAML
default
```

### logs

null

### Server environment

Server version:
Velocity 3.3.0-SNAPSHOT Build #393
Plugin list:
luckperms-Velocity#130，Trchat2.1.1,

Server version:
paper 1.20.4 #497
Plugin list:
luckperms-bukkit#130，Trchat2.1.1，PlaceholderAPI

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/9451980664
