### ISSUE TITLE
[issue] Anvil error happens when I install the Bank plugin

### ISSUE THREAD

**Issue by 1640946640** [FlickerProjects/TrChat#417]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

look at this:https://github.com/AshleyThew/Bank/issues/6
`[Minecraft]: Could not pass event PrepareAnvilEvent to TrChat v2.1.0 java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setDisplayNameComponent([Lnet/md_5/bungee/api/chat/BaseComponent;)V at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:51) ~[?:?] at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:42) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.util.ItemModifierKt.modifyMeta(ItemModifier.kt:44) ~[?:?] at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange.onAnvilCraft(ListenerAnvilChange.kt:42) ~[?:?] at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_371] at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-5a600445] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-5a600445] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-5a600445] at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1105) [CraftEventFactory.class:git-CatServer-1.12.2-5a600445] at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:377) [afs.class:?] at net.minecraft.inventory.ContainerRepair.func_82850_a(ContainerRepair.java:489) [afs.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147349_a(NetHandlerPlayServer.java:2873) [pa.class:?] at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:59) [lh.class:?] at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:11) [lh.class:?] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_371] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_371] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:750) [?:1.8.0_371] [00:21:37] [Craft Scheduler Thread - 861/INFO] []: [Bank] Running LoansDeadlineManager [00:21:37] [Craft Scheduler Thread - 861/INFO] []: [Bank] Handling Loans Deadlines [00:21:52] [Server thread/ERROR] [Minecraft]: Could not pass event PrepareAnvilEvent to TrChat v2.1.0 java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setDisplayNameComponent([Lnet/md_5/bungee/api/chat/BaseComponent;)V at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:51) ~[?:?] at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:42) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.util.ItemModifierKt.modifyMeta(ItemModifier.kt:44) ~[?:?] at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange.onAnvilCraft(ListenerAnvilChange.kt:42) ~[?:?] at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_371] at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-5a600445] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-5a600445] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-5a600445] at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1105) [CraftEventFactory.class:git-CatServer-1.12.2-5a600445] at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:377) [afs.class:?] at net.minecraft.inventory.ContainerRepair.func_82850_a(ContainerRepair.java:489) [afs.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147349_a(NetHandlerPlayServer.java:2873) [pa.class:?] at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:59) [lh.class:?] at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:11) [lh.class:?] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_371] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_371] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:750) [?:1.8.0_371]`

### configuration file

```YAML
no
```

### logs

none

### Server environment

Server version:
...
Plugin list:
...

**Comment by ItsFlicker** [comment]
Use 2.1.2
https://github.com/TrPlugins/TrChat/actions/runs/9451980664
