### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by hutuY** [FlickerProjects/TrChat#42]
不明白的问题，使用的paper-1.18.1-85 java17 
> [13:54:39 WARN]: java.lang.NoSuchFieldException: playerConnection at class net.minecraft.server.level.EntityPlayer
> [13:54:39 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
> [13:54:39 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
> [13:54:39 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
> [13:54:39 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
> [13:54:39 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
> [13:54:39 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:36)
> [13:54:39 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> [13:54:39 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [13:54:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [13:54:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [13:54:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ItsFlicker** [comment]
请更新到1.90-R5
