### ISSUE TITLE
[功能] 前缀HEX颜色支持

### ISSUE THREAD

**Issue by bluefish-08** [FlickerProjects/TrChat#426]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

希望聊天中的前缀可以使用HEX颜色代码，目前只能使用mc的颜色格式，使用hex颜色会变成如下：
![5a2327afb41d8dcb1499523cd5521c2b](https://github.com/user-attachments/assets/dc4d45f8-0a71-48c8-b78c-91da0f5ab071)

**Comment by ItsFlicker** [comment]
https://trchat.trixey.cc/guide/colors
