### ISSUE TITLE
[功能] 增加1.21.1支持

### ISSUE THREAD

**Issue by mjiangmc** [FlickerProjects/TrChat#427]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
增加对1.21.1的支持在1.21.1服务器端上无法使用trchat
```

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/10385139571

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/10752455117

**Comment by HiTech0926** [comment]
能否重新发一下构建？过期了，自己构建的话报错，一个mcitd.cn:8001的链接没了

**Comment by HiTech0926** [comment]
`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':project:common:compileKotlin'.
> Could not resolve all files for configuration ':project:common:compileClasspath'.
   > Could not resolve io.izzel.taboolib:bukkit-ui-legacy:6.2.0-beta5-dev.
     Required by:
         project :project:common
      > Could not resolve io.izzel.taboolib:bukkit-ui-legacy:6.2.0-beta5-dev.
         > Could not get resource 'http://mcitd.cn:8081/repository/releases/io/izzel/taboolib/bukkit-ui-legacy/6.2.0-beta5-dev/bukkit-ui-legacy-6.2.0-beta5-dev.pom'.
            > Could not GET 'http://mcitd.cn:8081/repository/releases/io/izzel/taboolib/bukkit-ui-legacy/6.2.0-beta5-dev/bukkit-ui-legacy-6.2.0-beta5-dev.pom'.
               > Connect to mcitd.cn:8081 [mcitd.cn/122.246.72.183] failed: Connection refused: getsockopt
      > Could not resolve io.izzel.taboolib:bukkit-ui-legacy:6.2.0-beta5-dev.
         > Could not get resource 'https://papermc.io/repo/repository/maven-public/io/izzel/taboolib/bukkit-ui-legacy/6.2.0-beta5-dev/bukkit-ui-legacy-6.2.0-beta5-dev.pom'.
            > Could not GET 'https://papermc.io/repo/repository/maven-public/io/izzel/taboolib/bukkit-ui-legacy/6.2.0-beta5-dev/bukkit-ui-legacy-6.2.0-beta5-dev.pom'. Received status code 403 from server: Forbidden
   > Could not resolve io.izzel.taboolib:bukkit-ui-modern:6.2.0-beta5-dev.
     Required by:
`

**Comment by ItsFlicker** [comment]
> 能否重新发一下构建？过期了，自己构建的话报错，一个mcitd.cn:8001的链接没了

2.2.1-test1
