### ISSUE TITLE
[issue] TrChat-2.2.0-beta2与最新版的itemadder冲突

### ISSUE THREAD

**Issue by CCjun6** [FlickerProjects/TrChat#439]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

ia以及前置的版本:
ItemsAdder_4.0.2-beta-release-10
LoneLibs_1.0.58

把它和trchat2.2.0-beat2放在一起就会复现
无法打出任何字 打一个字就会报错  删除掉ia以及前置就会正常  

### configuration file

```YAML
默认生成的配置文件就会发生错误 没有任何改动
```

### logs

完整的日志: https://mclo.gs/zz1RBSi

部分日志截图
![image](https://github.com/user-attachments/assets/9b51f504-4bdc-47dc-8910-fe98a6b3b531)

### Server environment

Server version:
...Current Purpur Version: 1.21.1-2304-dee41bc (MC: 1.21.1)*
* You are running the latest version
Plugin list:
...
![image](https://github.com/user-attachments/assets/e33b988e-ceba-4cab-934c-b9257a3553b6)

**Comment by CCjun6** [comment]
在反馈个问题 输入trchat reload 会有很长的报错
![image](https://github.com/user-attachments/assets/3ff0eafa-ecaa-44f7-9544-39330f2c886a)

**Comment by ItsFlicker** [comment]
ia改了api
而且不知道改成什么了

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/10869239536
