### ISSUE TITLE
[Feature] 请问没有数据库能正常使用吗？

### ISSUE THREAD

**Issue by cqw-acq** [FlickerProjects/TrChat#443]
### Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### Detailed description

就是我的服务器无法安装数据库软件，请问还能正常使用吗？

**Comment by ItsFlicker** [comment]
可以
