### ISSUE TITLE
[功能] 在1.12.2spigot插件服聊天栏中输入[inv]不能展示自己的背包

### ISSUE THREAD

**Issue by orange1184258252** [FlickerProjects/TrChat#449]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

1.在聊天栏中输入[inv]不能展示自己的背包
2.输入[ender]也没有用
但是输入%i或者[i]可以展示手上的物品

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/11423821464
