### ISSUE TITLE
增加一个强制让玩家使用敏感词过滤系统的功能

### ISSUE THREAD

**Issue by rewsdjad1** [FlickerProjects/TrChat#45]
如果玩家不去启用敏感词系统，那么敏感词系统就不会对他有任何效果。那这样的话，替换告示牌和铁砧就没有用了，玩家可以选择自己关掉敏感词然后再去使用告示牌和铁砧。并且许多玩家都不知道如何去打开敏感词系统，基本上没有几个玩家会自己手动去打开这个功能。

我建议可以在配置文件里面增加一个强制让所有玩家都必须使用敏感词系统的设置。

大概是这样：
`Force_Players_Use_Chat_Filter: true/false`
`Force_Players_Use_Sign_Filter: true/false`
`Force_Players_Use_Anvil_Filter: true/false`
`Force_Players_Use_Item_Filter: true/false`

**Comment by konsheng** [comment]
应该是敏感词替换，屏蔽的话就看不到消息了

**Comment by ItsFlicker** [comment]
只要玩家没有trchat.bypass.filter权限，用铁砧或告示牌都会有屏蔽效果
那个开关只对看到的聊天起效果

**Comment by ItsFlicker** [comment]
不过现在聊天屏蔽默认是关闭的(bug)

**Comment by rewsdjad1** [comment]
> 不过现在聊天屏蔽默认是关闭的(bug)

那也就是说以后会增加玩家强制使用聊天屏蔽吗

**Comment by ItsFlicker** [comment]
现在已经默认开启屏蔽了
只要没有权限就不能关闭
