### ISSUE TITLE
function.yml里的shareUrl貌似是无效的？

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [FlickerProjects/TrChat#53]
如题，写出来还是MC默认的URL的形式
![QQ截图20220111200902](https://user-images.githubusercontent.com/45261195/148940080-c5e3eae7-3245-4132-8ace-52174a655496.png)

**Comment by Aira-Sakuranomiya** [comment]
经测试，只要在formats.yml中将聊天颜色清除即可正常，看来是function.yml中的正则检测会把颜色代码也算在里面

**Comment by ItsFlicker** [comment]
换为`((https|http|ftp|rtsp|mms)?:\/\/)[^\s]+`就可以使用了
