### ISSUE TITLE
跨服启用支持问题

### ISSUE THREAD

**Issue by MCJiaoLong** [FlickerProjects/TrChat#58]
跨服端:waterfall-1.18-475
子服端:spigot-1.16.5
问题:配置文件,跨服和子服端都已启用跨服聊天(如图),可是发送 [ !all 内容 ] 还是显示未启用跨服支持,暂不支持喊话
图片:
![8)27 PZ78(UI1UM`B5G)WWG](https://user-images.githubusercontent.com/75253383/150095519-b8112e3c-d9c4-4fc8-90a6-ea94670be72c.png)
![L0)G4)1POPY9( BETV536LD](https://user-images.githubusercontent.com/75253383/150095414-00180b52-6dc2-4153-891d-11f64614c30b.png)
![ABA MOLE~DEAX@@4_JZ 30F](https://user-images.githubusercontent.com/75253383/150095426-577f7c50-3567-4107-b3e2-bdfe3cd9866f.png)
![}J2O_0C(1Y2K9C0QP78640I](https://user-images.githubusercontent.com/75253383/150095446-128cdea5-5d44-44fc-90c0-7288a11d2759.png)
)

**Comment by ItsFlicker** [comment]
检查一下spigot.yml里的settings.bungeecord有没有设为true
