### ISSUE TITLE
TrChat的多个BUG与建议

### ISSUE THREAD

**Issue by MrLaoGe** [FlickerProjects/TrChat#60]
1. 经过测试 R5 版本无法在 1.16 环境下使用
2. 建议新增跨服聊天的指定发送指定子服的功能 (或新增服务器屏蔽来自Trchat的跨服消息)
问题案例：BC群组服存在 ABC D 服务器。ABC服务器需要跨服聊天，D服务器独立聊天。
测试现存问题D不管是否将bungeecord:false 和 FORCE-GLOBAL:false 都会收到来着 ABC 服务器的聊天信息. 无法做到聊天隔离
3. 经过测试频道功能无法实现跨服聊天

服务器版本：1.16.5 paper 、1.17.1 paper 、BC

**Comment by ItsFlicker** [comment]
功能2已实现 (需要重新生成channels.yml)

**Comment by MrLaoGe** [comment]
好的, 感谢更新

**Comment by ItsFlicker** [comment]
1.16 无法使用有什么报错或日志吗

**Comment by MrLaoGe** [comment]
那个刚刚测试了, 是由于BC端的R版本和子服的R版本不匹配，导致无法握手产生的，应该是属于我个人的问题...QWQ

**Comment by ItsFlicker** [comment]
尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有问题3
