### ISSUE TITLE
新版物品在展示时无法显示中文

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [FlickerProjects/TrChat#61]
![QQ截图20220122212112](https://user-images.githubusercontent.com/45261195/150640153-201a9c89-d734-4a2f-b181-a42eae2dcea6.png)

**Comment by ItsFlicker** [comment]
检查下function.yml里的ITEM-SHOW.ORIGIN-NAME是否为false

**Comment by ItsFlicker** [comment]
![image](https://user-images.githubusercontent.com/34670283/151287140-ade3d1b9-3b69-4d49-a670-edca63234f60.png)

**Comment by Aira-Sakuranomiya** [comment]
这是调用的哪里的啊...是不是得删除重新载入新版

**Comment by Aira-Sakuranomiya** [comment]
![image](https://user-images.githubusercontent.com/45261195/151359972-7296a8b1-838b-44be-ab92-bae42bc35e28.png)
使用最新版Paper+PlaceholderAPI+TrChat就可以复现这个问题...（均为默认配置）

**Comment by ItsFlicker** [comment]
知道什么问题了

**Comment by ItsFlicker** [comment]
已修复
