### ISSUE TITLE
1.8.8 无法跨服聊天

### ISSUE THREAD

**Issue by Hua-Fan-Yang** [FlickerProjects/TrChat#64]
没有任何报错只显示未启用跨服聊天 设置以及spigot全部都开启了bc 其他服务器可以 只有1.8的传送大厅不行

**Comment by ItsFlicker** [comment]
检查下settings.yml里的GENERAL.PROXY是否为BUNGEE

**Comment by Hua-Fan-Yang** [comment]
这是来自阳阳邮箱的自动回复邮件。你好，我最近很忙，无法亲自回复你的邮件。我将在忙完后，尽快给你回复。

**Comment by ItsFlicker** [comment]
还有开服时是否显示已支持Bungee通讯

**Comment by ItsFlicker** [comment]
@Hua-Fan-Yang

**Comment by ItsFlicker** [comment]
尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题

**Comment by YyangHuiL** [comment]
这是来自阳阳邮箱的自动回复邮件。你好，我最近很忙，无法亲自回复你的邮件。我将在忙完后，尽快给你回复。

**Comment by ItsFlicker** [comment]
Fixed in PRE-4

**Comment by YyangHuiL** [comment]
这是来自阳阳邮箱的自动回复邮件。你好，我最近很忙，无法亲自回复你的邮件。我将在忙完后，尽快给你回复。
