### ISSUE TITLE
veolicity跨服聊天无效

### ISSUE THREAD

**Issue by CuteLittleSky** [FlickerProjects/TrChat#72]
rt,聊天栏不显示,跨服不显示,仅发送消息的服控制台会显示

**Comment by ItsFlicker** [comment]
尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题

**Comment by CuteLittleSky** [comment]
> 尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题

依旧无效

而且似乎hover与command无效了

**Comment by ItsFlicker** [comment]
> > 尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题
> 
> 依旧无效
> 
> 而且似乎hover与command无效了

hover与command PRE-2已修复

**Comment by ItsFlicker** [comment]
> > 尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题
> 
> 依旧无效
> 
> 而且似乎hover与command无效了

尝试 https://github.com/FlickerProjects/TrChat/actions/runs/2088129128

**Comment by CuteLittleSky** [comment]
> > > 尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题
> > 
> > 
> > 依旧无效
> > 而且似乎hover与command无效了
> 
> 尝试 https://github.com/FlickerProjects/TrChat/actions/runs/2088129128

依然无法解决 )

屏蔽词好像会屏蔽聊天栏输出的所有信息 如果玩家名字含屏蔽词会直接屏蔽玩家名字那一部分

**Comment by ItsFlicker** [comment]
用的不是modern模式吗

**Comment by ItsFlicker** [comment]
> 屏蔽词好像会屏蔽聊天栏输出的所有信息 如果玩家名字含屏蔽词会直接屏蔽玩家名字那一部分

重新生成下filter.yml

**Comment by CuteLittleSky** [comment]
> 用的不是modern模式吗

突然发现不是 稍等我改成modern试试..
