### ISSUE TITLE
Trchat和TAB插件冲突

### ISSUE THREAD

**Issue by cat-catmiao** [FlickerProjects/TrChat#78]
Trchat会导致TAB的变量失效，他们一起安装到BC端后，TAB的变量不会显示变量内容。

![image](https://user-images.githubusercontent.com/83876597/154684000-825142f5-ffca-4d53-a535-c992c73c4b7b.png)

**Comment by ItsFlicker** [comment]
2.0.0-PRE-1 Fixed
