### ISSUE TITLE
TrChat-1.82 导致玩家延迟异常

### ISSUE THREAD

**Issue by Syscat20** [FlickerProjects/TrChat#8]
我正使用TrChat 1.82版本。服务器重启后再进入服务器会变得很卡，玩家Ping值飙升(到几千)，但用Plugman把TrChat卸载后，服务器就恢复正常了，再次载入后依旧是老样子。不过我在服务器后台并没有看到什么报错，请问这还有办法解决吗（

**Comment by Syscat20** [comment]
忘记了（
是1.17.1的版本 核心Sugarcane

**Comment by ItsFlicker** [comment]
尝试使用1.83版本

**Comment by ItsFlicker** [comment]
[https://github.com/FlickerProjects/TrChat/releases/tag/1.90](url) 已修复
