### ISSUE TITLE
Trchat和nlogin登录插件报错

### ISSUE THREAD

**Issue by lovemercer** [FlickerProjects/TrChat#81]
https://github.com/Arasple/TrChat/blob/master/src/main/java/me/arasple/mc/trchat/bungee/ListenerBungeeTransfer.java#L27

The developer are handling PluginMessageEvent incorrectly
Ask for the developer to read the content only if is "TrChat" channel

**Comment by lovemercer** [comment]
BC内报错

**Comment by lovemercer** [comment]
BC 插件冲突导致nlogin 无法正常登录

**Comment by ItsFlicker** [comment]
https://github.com/FlickerProjects/TrChat/blob/master/src/main/kotlin/me/arasple/mc/trchat/internal/proxy/bungee/ListenerBungeeTransfer.kt

我的改版中没有这个问题

**Comment by ItsFlicker** [comment]
尝试2.0.0-PRE-1是否还有此问题

**Comment by ItsFlicker** [comment]
https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1

**Comment by lovemercer** [comment]
此问题已解决，谢谢修复
