### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by DJelly4K** [FlickerProjects/TrChat#89]
Error on load
log: https://pastebin.com/dG0rxkXJ
core: [Mirai](https://github.com/etil2jz/Mirai/) (a pufferfish <= paper fork) 1.18.2

**Comment by ItsFlicker** [comment]
function.yml或formats.yml写的有问题

**Comment by DJelly4K** [comment]
> function.yml或formats.yml写的有问题

formats.yml: https://pastebin.com/99GtepA8
function.yml: https://pastebin.com/qvL7eUWL

没有问题……吧
function.yml我没动过

**Comment by ItsFlicker** [comment]
Global 以下都没写msg

**Comment by DJelly4K** [comment]
> Global 以下都没写msg

（要写吗）
好的我去试试，谢谢

**Comment by DJelly4K** [comment]
> Global 以下都没写msg

https://pastebin.com/H6XcUSVq
补上去了，restart过后问题依旧存在
![image](https://user-images.githubusercontent.com/68630033/158046971-8901b321-defd-48d3-b37f-9e80529b9a3b.png)

**Comment by ItsFlicker** [comment]
> https://pastebin.com/H6XcUSVq

没补啊

**Comment by DJelly4K** [comment]
> > https://pastebin.com/H6XcUSVq
> 
> 没补啊

？？？不是在global,vip1和vip2那里都要写上msg还是
![image](https://user-images.githubusercontent.com/68630033/158047048-1e85f609-8dce-4224-97ad-f5d720c079c2.png)

**Comment by ItsFlicker** [comment]
![image](https://user-images.githubusercontent.com/34670283/158047063-1c66edd5-a20a-4ba4-8c5f-f9b43167c180.png)
我说这个部分

**Comment by DJelly4K** [comment]
> ![image](https://user-images.githubusercontent.com/34670283/158047063-1c66edd5-a20a-4ba4-8c5f-f9b43167c180.png) 我说这个部分

啊（
我去试试

**Comment by DJelly4K** [comment]
> Reference in

可以了，谢谢

**Comment by DJelly4K** [comment]
> ![image](https://user-images.githubusercontent.com/34670283/158047063-1c66edd5-a20a-4ba4-8c5f-f9b43167c180.png) 我说这个部分

可以了，谢谢作者的帮助

**Comment by ItsFlicker** [comment]
不用谢
