### ISSUE TITLE
两个使用问题

### ISSUE THREAD

**Issue by Moki0** [FlickerProjects/TrChat#9]
1.
不在同一个子服AT没有声音提示
2.
发送 <AT:任意内容> 会显示绿色的@任意内容
直接发送玩家ID不会自动转换为AT （之前是可以的）

**Comment by Moki0** [comment]
是的，也许可以禁止玩家发送这样的信息，或者给玩家发送的做个标记，不给予处理

**Comment by ItsFlicker** [comment]
已修复
