### ISSUE TITLE
无法实现@人 Mention方法的冷却时间

### ISSUE THREAD

**Issue by Xiaye2332** [FlickerProjects/TrChat#90]
`  MENTION:
    ENABLE: true
    SELF-MENTION: true
    FORMAT: '&r &a@&2{0}&r '
    COOLDOWNS: 300
    NOTIFY: true`

无论设置COOLDOWNS为多久，玩家都可以一直发送

**Comment by ItsFlicker** [comment]
尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题
