### ISSUE TITLE
数据库无法使用?

### ISSUE THREAD

**Issue by 1152279175** [FlickerProjects/TrChat#93]
DATABASE:
    enable: true
填写数据库信息后，开服仍然是使用sqlite,  data.db
随便填写，开服也不会有任何报错？？

**Comment by 1152279175** [comment]
DATABASE:
    enable: true
填写数据库信息后，开服仍然是使用sqlite,  data.db

**Comment by ItsFlicker** [comment]
https://github.com/FlickerProjects/TrChat/actions/runs/2028318317

**Comment by ItsFlicker** [comment]
> https://github.com/FlickerProjects/TrChat/actions/runs/2028318317

Fixed
