### ISSUE TITLE
渐变色问题

### ISSUE THREAD

**Issue by chjiatai** [FlickerProjects/TrChat#94]
default-color: '<g:#ffffff:#ffaaaa>'
 这样写有错误吗？
 没有任何反应
 R8的版本

**Comment by ItsFlicker** [comment]
尝试使用2.0.0-PRE-1

**Comment by chjiatai** [comment]
> 尝试使用2 . 0 . 0-1之前

是修复版的吗？在哪里下载插件

**Comment by ItsFlicker** [comment]
https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1
