### ISSUE TITLE
2.0-test8 @玩家会变成@自己

### ISSUE THREAD

**Issue by CuteLittleSky** [FlickerProjects/TrChat#96]
例如我叫AAA，我@了BBB,正常应该是
AAA: @BBB
但实际是
AAA: @AAA

**Comment by ItsFlicker** [comment]
test-9已修复 (忘传了)

**Comment by ItsFlicker** [comment]
gradle插件站炸了 暂时构建不出来

**Comment by ItsFlicker** [comment]
https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1
