### ISSUE TITLE
功能建议：TAB补全黑名单

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [FlickerProjects/TrChat#98]
如题，希望可以设定某些玩家不能被补全，这样管理悄悄上线不容易被使用这种方式发现

**Comment by ItsFlicker** [comment]
是仅trchat提供的命令补全还是所有的补全黑名单

**Comment by Aira-Sakuranomiya** [comment]
TrChat的，比如说/msg出来的补全

**Comment by Aira-Sakuranomiya** [comment]
如果可以的话，希望可以hook Essentials的隐身，隐身时无法补全这个玩家的名字

**Comment by ItsFlicker** [comment]
PRE-4新增/trchat vanish命令
