### ISSUE TITLE
1.16.5无法启动插件

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [FlickerProjects/TrChat#99]
![屏幕截图 2022-03-29 000016](https://user-images.githubusercontent.com/45261195/160439509-54babd6d-6b72-4012-83e3-ab30bae21922.jpg)

如图
版本: TrChat-2.0.0-PRE-1

**Comment by Aira-Sakuranomiya** [comment]
我这服务端在生产环境不太方便这样测试，可以知道的是1.9可以正常工作

**Comment by ItsFlicker** [comment]
PRE-2已修复
